const initialWords = [
  // --- Part 1 (1〜70語: 名詞・身の回り・学校1) ---
  { id: 1, part: "part1", word: "book", meaning: "本" },
  { id: 2, part: "part1", word: "pen", meaning: "ペン" },
  { id: 3, part: "part1", word: "pencil", meaning: "鉛筆" },
  { id: 4, part: "part1", word: "desk", meaning: "つくえ" },
  { id: 5, part: "part1", word: "chair", meaning: "いす" },
  { id: 6, part: "part1", word: "bag", meaning: "かばん" },
  { id: 7, part: "part1", word: "notebook", meaning: "ノート" },
  { id: 8, part: "part1", word: "box", meaning: "箱" },
  { id: 9, part: "part1", word: "clock", meaning: "時計" },
  { id: 10, part: "part1", word: "picture", meaning: "写真・絵" },
  { id: 11, part: "part1", word: "computer", meaning: "コンピュータ" },
  { id: 12, part: "part1", word: "phone", meaning: "電話" },
  { id: 13, part: "part1", word: "school", meaning: "学校" },
  { id: 14, part: "part1", word: "classroom", meaning: "教室" },
  { id: 15, part: "part1", word: "teacher", meaning: "先生" },
  { id: 16, part: "part1", word: "student", meaning: "生徒" },
  { id: 17, part: "part1", word: "friend", meaning: "友達" },
  { id: 18, part: "part1", word: "class", meaning: "授業・クラス" },
  { id: 19, part: "part1", word: "homework", meaning: "宿題" },
  { id: 20, part: "part1", word: "test", meaning: "テスト" },
  { id: 21, part: "part1", word: "house", meaning: "家" },
  { id: 22, part: "part1", word: "home", meaning: "家庭・家へ" },
  { id: 23, part: "part1", word: "room", meaning: "部屋" },
  { id: 24, part: "part1", word: "door", meaning: "ドア" },
  { id: 25, part: "part1", word: "window", meaning: "窓" },
  { id: 26, part: "part1", word: "table", meaning: "テーブル" },
  { id: 27, part: "part1", word: "bed", meaning: "ベッド" },
  { id: 28, part: "part1", word: "kitchen", meaning: "台所" },
  { id: 29, part: "part1", word: "park", meaning: "公園" },
  { id: 30, part: "part1", word: "station", meaning: "駅" },
  { id: 31, part: "part1", word: "shop", meaning: "店" },
  { id: 32, part: "part1", word: "store", meaning: "店" },
  { id: 33, part: "part1", word: "hospital", meaning: "病院" },
  { id: 34, part: "part1", word: "library", meaning: "図書館" },
  { id: 35, part: "part1", word: "bus", meaning: "バス" },
  { id: 36, part: "part1", word: "car", meaning: "車" },
  { id: 37, part: "part1", word: "train", meaning: "電車" },
  { id: 38, part: "part1", word: "bike", meaning: "自転車" },
  { id: 39, part: "part1", word: "plane", meaning: "飛行機" },
  { id: 40, part: "part1", word: "taxi", meaning: "タクシー" },
  { id: 41, part: "part1", word: "father", meaning: "お父さん" },
  { id: 42, part: "part1", word: "mother", meaning: "お母さん" },
  { id: 43, part: "part1", word: "parent", meaning: "親" },
  { id: 44, part: "part1", word: "brother", meaning: "兄弟（兄・弟）" },
  { id: 45, part: "part1", word: "sister", meaning: "姉妹（姉・妹）" },
  { id: 46, part: "part1", word: "son", meaning: "息子" },
  { id: 47, part: "part1", word: "daughter", meaning: "娘" },
  { id: 48, part: "part1", word: "family", meaning: "家族" },
  { id: 49, part: "part1", word: "man", meaning: "男性" },
  { id: 50, part: "part1", word: "woman", meaning: "女性" },
  { id: 51, part: "part1", word: "boy", meaning: "男の子" },
  { id: 52, part: "part1", word: "girl", meaning: "女の子" },
  { id: 53, part: "part1", word: "baby", meaning: "赤ん坊" },
  { id: 54, part: "part1", word: "child", meaning: "子供" },
  { id: 55, part: "part1", word: "dog", meaning: "犬" },
  { id: 56, part: "part1", word: "cat", meaning: "猫" },
  { id: 57, part: "part1", word: "bird", meaning: "鳥" },
  { id: 58, part: "part1", word: "fish", meaning: "魚" },
  { id: 59, part: "part1", word: "bear", meaning: "クマ" },
  { id: 60, part: "part1", word: "rabbit", meaning: "ウサギ" },
  { id: 61, part: "part1", word: "apple", meaning: "りんご" },
  { id: 62, part: "part1", word: "banana", meaning: "バナナ" },
  { id: 63, part: "part1", word: "orange", meaning: "オレンジ" },
  { id: 64, part: "part1", word: "water", meaning: "水" },
  { id: 65, part: "part1", word: "milk", meaning: "牛乳" },
  { id: 66, part: "part1", word: "tea", meaning: "お茶・紅茶" },
  { id: 67, part: "part1", word: "juice", meaning: "ジュース" },
  { id: 68, part: "part1", word: "coffee", meaning: "コーヒー" },
  { id: 69, part: "part1", word: "bread", meaning: "パン" },
  { id: 70, part: "part1", word: "rice", meaning: "ご飯・米" },

  // --- Part 2 (71〜140語: 動詞1) ---
  { id: 71, part: "part2", word: "go", meaning: "行く" },
  { id: 72, part: "part2", word: "come", meaning: "来る" },
  { id: 73, part: "part2", word: "see", meaning: "見る・会う" },
  { id: 74, part: "part2", word: "look", meaning: "見る" },
  { id: 75, part: "part2", word: "listen", meaning: "聴く" },
  { id: 76, part: "part2", word: "hear", meaning: "聞こえる" },
  { id: 77, part: "part2", word: "speak", meaning: "話す" },
  { id: 78, part: "part2", word: "talk", meaning: "話す・しゃべる" },
  { id: 79, part: "part2", word: "say", meaning: "言う" },
  { id: 80, part: "part2", word: "eat", meaning: "食べる" },
  { id: 81, part: "part2", word: "drink", meaning: "飲む" },
  { id: 82, part: "part2", word: "read", meaning: "読む" },
  { id: 83, part: "part2", word: "write", meaning: "書く" },
  { id: 84, part: "part2", word: "study", meaning: "勉強する" },
  { id: 85, part: "part2", word: "play", meaning: "遊ぶ・(スポーツを)する" },
  { id: 86, part: "part2", word: "run", meaning: "走る" },
  { id: 87, part: "part2", word: "walk", meaning: "歩く" },
  { id: 88, part: "part2", word: "swim", meaning: "泳ぐ" },
  { id: 89, part: "part2", word: "sing", meaning: "歌う" },
  { id: 90, part: "part2", word: "dance", meaning: "踊る" },
  { id: 91, part: "part2", word: "use", meaning: "使う" },
  { id: 92, part: "part2", word: "make", meaning: "作る" },
  { id: 93, part: "part2", word: "cook", meaning: "料理する" },
  { id: 94, part: "part2", word: "buy", meaning: "買う" },
  { id: 95, part: "part2", word: "help", meaning: "手伝う・助ける" },
  { id: 96, part: "part2", word: "like", meaning: "好む・好き" },
  { id: 97, part: "part2", word: "love", meaning: "愛する・大好き" },
  { id: 98, part: "part2", word: "want", meaning: "欲しい" },
  { id: 99, part: "part2", word: "know", meaning: "知っている" },
  { id: 100, part: "part2", word: "think", meaning: "考える・思う" },
  { id: 101, part: "part2", word: "clean", meaning: "掃除する" },
  { id: 102, part: "part2", word: "wash", meaning: "洗う" },
  { id: 103, part: "part2", word: "open", meaning: "開ける" },
  { id: 104, part: "part2", word: "close", meaning: "閉める" },
  { id: 105, part: "part2", word: "start", meaning: "始まる・始める" },
  { id: 106, part: "part2", word: "stop", meaning: "止まる・止める" },
  { id: 107, part: "part2", word: "live", meaning: "住んでいる" },
  { id: 108, part: "part2", word: "work", meaning: "働く" },
  { id: 109, part: "part2", word: "have", meaning: "持っている・食べる" },
  { id: 110, part: "part2", word: "take", meaning: "連れて行く・（写真を）撮る" },
  { id: 111, part: "part2", word: "get", meaning: "得る・手に入れる" },
  { id: 112, part: "part2", word: "give", meaning: "与える・あげる" },
  { id: 113, part: "part2", word: "find", meaning: "見つける" },
  { id: 114, part: "part2", word: "ask", meaning: "尋ねる・頼む" },
  { id: 115, part: "part2", word: "tell", meaning: "話す・教える" },
  { id: 116, part: "part2", word: "show", meaning: "見せる" },
  { id: 117, part: "part2", word: "teach", meaning: "教える" },
  { id: 118, part: "part2", word: "learn", meaning: "学ぶ" },
  { id: 119, part: "part2", word: "meet", meaning: "会う" },
  { id: 120, part: "part2", word: "visit", meaning: "訪問する" },
  { id: 121, part: "part2", word: "stay", meaning: "滞在する・とどまる" },
  { id: 122, part: "part2", word: "enjoy", meaning: "楽しむ" },
  { id: 123, part: "part2", word: "finish", meaning: "終わらせる" },
  { id: 124, part: "part2", word: "try", meaning: "試す・努力する" },
  { id: 125, part: "part2", word: "need", meaning: "必要とする" },
  { id: 126, part: "part2", word: "wait", meaning: "待つ" },
  { id: 127, part: "part2", word: "call", meaning: "呼ぶ・電話する" },
  { id: 128, part: "part2", word: "put", meaning: "置く" },
  { id: 129, part: "part2", word: "bring", meaning: "持ってくる" },
  { id: 130, part: "part2", word: "carry", meaning: "運ぶ" },
  { id: 131, part: "part2", word: "wear", meaning: "着ている" },
  { id: 132, part: "part2", word: "smile", meaning: "ほほえむ" },
  { id: 133, part: "part2", word: "cry", meaning: "泣く" },
  { id: 134, part: "part2", word: "fly", meaning: "飛ぶ" },
  { id: 135, part: "part2", word: "drive", meaning: "運転する" },
  { id: 136, part: "part2", word: "turn", meaning: "曲がる・回る" },
  { id: 137, part: "part2", word: "stand", meaning: "立つ" },
  { id: 138, part: "part2", word: "sit", meaning: "座る" },
  { id: 139, part: "part2", word: "sleep", meaning: "寝る" },
  { id: 140, part: "part2", word: "wake", meaning: "起きる・目を覚ます" },

  // --- Part 3 (141〜210語: 形容詞・副詞1) ---
  { id: 141, part: "part3", word: "big", meaning: "大きい" },
  { id: 142, part: "part3", word: "small", meaning: "小さい" },
  { id: 143, part: "part3", word: "good", meaning: "良い" },
  { id: 144, part: "part3", word: "bad", meaning: "悪い" },
  { id: 145, part: "part3", word: "new", meaning: "新しい" },
  { id: 146, part: "part3", word: "old", meaning: "古い・年をとった" },
  { id: 147, part: "part3", word: "happy", meaning: "幸せな・嬉しい" },
  { id: 148, part: "part3", word: "sad", meaning: "悲しい" },
  { id: 149, part: "part3", word: "hot", meaning: "熱い・暑い" },
  { id: 150, part: "part3", word: "cold", meaning: "冷たい・寒い" },
  { id: 151, part: "part3", word: "warm", meaning: "暖かい" },
  { id: 152, part: "part3", word: "cool", meaning: "涼しい・かっこいい" },
  { id: 153, part: "part3", word: "high", meaning: "高い" },
  { id: 154, part: "part3", word: "low", meaning: "低い" },
  { id: 155, part: "part3", word: "long", meaning: "長い" },
  { id: 156, part: "part3", word: "short", meaning: "短い・背が低い" },
  { id: 157, part: "part3", word: "fast", meaning: "速い" },
  { id: 158, part: "part3", word: "slow", meaning: "遅い" },
  { id: 159, part: "part3", word: "busy", meaning: "忙しい" },
  { id: 160, part: "part3", word: "kind", meaning: "親切な" },
  { id: 161, part: "part3", word: "nice", meaning: "良い・素晴らしい" },
  { id: 162, part: "part3", word: "fine", meaning: "元気な・良い" },
  { id: 163, part: "part3", word: "glad", meaning: "嬉しい" },
  { id: 164, part: "part3", word: "early", meaning: "早く・早めに" },
  { id: 165, part: "part3", word: "late", meaning: "遅れて・遅く" },
  { id: 166, part: "part3", word: "always", meaning: "いつも" },
  { id: 167, part: "part3", word: "usually", meaning: "たいてい" },
  { id: 168, part: "part3", word: "often", meaning: "よく・しばしば" },
  { id: 169, part: "part3", word: "sometimes", meaning: "ときどき" },
  { id: 170, part: "part3", word: "today", meaning: "今日" },
  { id: 171, part: "part3", word: "tomorrow", meaning: "明日" },
  { id: 172, part: "part3", word: "yesterday", meaning: "昨日" },
  { id: 173, part: "part3", word: "now", meaning: "今" },
  { id: 174, part: "part3", word: "here", meaning: "ここ" },
  { id: 175, part: "part3", word: "there", meaning: "そこ・あそこ" },
  { id: 176, part: "part3", word: "easy", meaning: "簡単な" },
  { id: 177, part: "part3", word: "hard", meaning: "難しい・硬い" },
  { id: 178, part: "part3", word: "clean", meaning: "きれいな" },
  { id: 179, part: "part3", word: "dirty", meaning: "汚い" },
  { id: 180, part: "part3", word: "young", meaning: "若い" },
  { id: 181, part: "part3", word: "tall", meaning: "背が高い" },
  { id: 182, part: "part3", word: "heavy", meaning: "重い" },
  { id: 183, part: "part3", word: "light", meaning: "軽い・明るい" },
  { id: 184, part: "part3", word: "dark", meaning: "暗い" },
  { id: 185, part: "part3", word: "bright", meaning: "明るい" },
  { id: 186, part: "part3", word: "beautiful", meaning: "美しい" },
  { id: 187, part: "part3", word: "cute", meaning: "かわいい" },
  { id: 188, part: "part3", word: "famous", meaning: "有名な" },
  { id: 189, part: "part3", word: "popular", meaning: "人気がある" },
  { id: 190, part: "part3", word: "special", meaning: "特別な" },
  { id: 191, part: "part3", word: "different", meaning: "異なる・違う" },
  { id: 192, part: "part3", word: "same", meaning: "同じ" },
  { id: 193, part: "part3", word: "near", meaning: "近い" },
  { id: 194, part: "part3", word: "far", meaning: "遠い" },
  { id: 195, part: "part3", word: "rich", meaning: "豊かな・金持ちの" },
  { id: 196, part: "part3", word: "poor", meaning: "貧しい・かわいそうな" },
  { id: 197, part: "part3", word: "strong", meaning: "強い" },
  { id: 198, part: "part3", word: "weak", meaning: "弱い" },
  { id: 199, part: "part3", word: "hungry", meaning: "空腹の" },
  { id: 200, part: "part3", word: "thirsty", meaning: "のどが渇いた" },
  { id: 201, part: "part3", word: "tired", meaning: "疲れた" },
  { id: 202, part: "part3", word: "sick", meaning: "病気の" },
  { id: 203, part: "part3", word: "well", meaning: "元気に・うまく" },
  { id: 204, part: "part3", word: "together", meaning: "一緒に" },
  { id: 205, part: "part3", word: "again", meaning: "もう一度" },
  { id: 206, part: "part3", word: "also", meaning: "〜もまた" },
  { id: 207, part: "part3", word: "too", meaning: "〜もまた・あまりに" },
  { id: 208, part: "part3", word: "very", meaning: "とても" },
  { id: 209, part: "part3", word: "so", meaning: "とても・だから" },
  { id: 210, part: "part3", word: "well", meaning: "上手く" },

  // --- Part 4 (211〜280語: 代名詞・疑問詞・接続詞) ---
  { id: 211, part: "part4", word: "I", meaning: "私は" },
  { id: 212, part: "part4", word: "my", meaning: "私の" },
  { id: 213, part: "part4", word: "me", meaning: "私を・私に" },
  { id: 214, part: "part4", word: "mine", meaning: "私のもの" },
  { id: 215, part: "part4", word: "you", meaning: "あなたは" },
  { id: 216, part: "part4", word: "your", meaning: "あなたの" },
  { id: 217, part: "part4", word: "yours", meaning: "あなたのもの" },
  { id: 218, part: "part4", word: "he", meaning: "彼は" },
  { id: 219, part: "part4", word: "his", meaning: "彼の・彼のもの" },
  { id: 220, part: "part4", word: "him", meaning: "彼を・彼に" },
  { id: 221, part: "part4", word: "she", meaning: "彼女は" },
  { id: 222, part: "part4", word: "her", meaning: "彼女の・彼女を" },
  { id: 223, part: "part4", word: "hers", meaning: "彼女のもの" },
  { id: 224, part: "part4", word: "it", meaning: "それは" },
  { id: 225, part: "part4", word: "its", meaning: "それの" },
  { id: 226, part: "part4", word: "we", meaning: "私たちは" },
  { id: 227, part: "part4", word: "our", meaning: "私たちの" },
  { id: 228, part: "part4", word: "us", meaning: "私達を・私達に" },
  { id: 229, part: "part4", word: "ours", meaning: "私たちのもの" },
  { id: 230, part: "part4", word: "they", meaning: "彼らは・それらは" },
  { id: 231, part: "part4", word: "their", meaning: "彼らの・それらの" },
  { id: 232, part: "part4", word: "them", meaning: "彼らを・それらを" },
  { id: 233, part: "part4", word: "theirs", meaning: "彼らのもの" },
  { id: 234, part: "part4", word: "this", meaning: "これ・この" },
  { id: 235, part: "part4", word: "that", meaning: "あれ・あの" },
  { id: 236, part: "part4", word: "these", meaning: "これら" },
  { id: 237, part: "part4", word: "those", meaning: "あれら" },
  { id: 238, part: "part4", word: "what", meaning: "何" },
  { id: 239, part: "part4", word: "who", meaning: "誰" },
  { id: 240, part: "part4", word: "where", meaning: "どこ" },
  { id: 241, part: "part4", word: "when", meaning: "いつ" },
  { id: 242, part: "part4", word: "why", meaning: "なぜ" },
  { id: 243, part: "part4", word: "how", meaning: "どのように" },
  { id: 244, part: "part4", word: "which", meaning: "どちら" },
  { id: 245, part: "part4", word: "whose", meaning: "誰の" },
  { id: 246, part: "part4", word: "and", meaning: "〜と・そして" },
  { id: 247, part: "part4", word: "but", meaning: "しかし" },
  { id: 248, part: "part4", word: "or", meaning: "または" },
  { id: 249, part: "part4", word: "so", meaning: "だから" },
  { id: 250, part: "part4", word: "because", meaning: "なぜなら" },
  { id: 251, part: "part4", word: "if", meaning: "もし〜なら" },
  { id: 252, part: "part4", word: "when", meaning: "〜するとき" },
  { id: 253, part: "part4", word: "in", meaning: "〜の中に" },
  { id: 254, part: "part4", word: "on", meaning: "〜の上に" },
  { id: 255, part: "part4", word: "under", meaning: "〜の下に" },
  { id: 256, part: "part4", word: "at", meaning: "〜で" },
  { id: 257, part: "part4", word: "by", meaning: "〜のそばに・〜によって" },
  { id: 258, part: "part4", word: "for", meaning: "〜のために" },
  { id: 259, part: "part4", word: "to", meaning: "〜へ・〜に" },
  { id: 260, part: "part4", word: "from", meaning: "〜から" },
  { id: 261, part: "part4", word: "with", meaning: "〜と一緒に" },
  { id: 262, part: "part4", word: "without", meaning: "〜なしで" },
  { id: 263, part: "part4", word: "about", meaning: "〜について" },
  { id: 264, part: "part4", word: "of", meaning: "〜の" },
  { id: 265, part: "part4", word: "before", meaning: "〜の前に" },
  { id: 266, part: "part4", word: "after", meaning: "〜の後に" },
  { id: 267, part: "part4", word: "between", meaning: "〜の間に" },
  { id: 268, part: "part4", word: "behind", meaning: "〜の後ろに" },
  { id: 269, part: "part4", word: "front", meaning: "前" },
  { id: 270, part: "part4", word: "over", meaning: "〜の上に" },
  { id: 271, part: "part4", word: "into", meaning: "〜の中へ" },
  { id: 272, part: "part4", word: "out", meaning: "外へ" },
  { id: 273, part: "part4", word: "up", meaning: "上へ" },
  { id: 274, part: "part4", word: "down", meaning: "下へ" },
  { id: 275, part: "part4", word: "off", meaning: "離れて" },
  { id: 276, part: "part4", word: "all", meaning: "すべての" },
  { id: 277, part: "part4", word: "some", meaning: "いくつかの" },
  { id: 278, part: "part4", word: "any", meaning: "いくつかの（疑問・否定）" },
  { id: 279, part: "part4", word: "no", meaning: "ひとつも〜ない" },
  { id: 280, part: "part4", word: "every", meaning: "すべての" },

  // --- Part 5 (281〜350語: 曜日・月・季節・数字・時間) ---
  { id: 281, part: "part5", word: "Sunday", meaning: "日曜日" },
  { id: 282, part: "part5", word: "Monday", meaning: "月曜日" },
  { id: 283, part: "part5", word: "Tuesday", meaning: "火曜日" },
  { id: 284, part: "part5", word: "Wednesday", meaning: "水曜日" },
  { id: 285, part: "part5", word: "Thursday", meaning: "木曜日" },
  { id: 286, part: "part5", word: "Friday", meaning: "金曜日" },
  { id: 287, part: "part5", word: "Saturday", meaning: "土曜日" },
  { id: 288, part: "part5", word: "January", meaning: "1月" },
  { id: 289, part: "part5", word: "February", meaning: "2月" },
  { id: 290, part: "part5", word: "March", meaning: "3月" },
  { id: 291, part: "part5", word: "April", meaning: "4月" },
  { id: 292, part: "part5", word: "May", meaning: "5月" },
  { id: 293, part: "part5", word: "June", meaning: "6月" },
  { id: 294, part: "part5", word: "July", meaning: "7月" },
  { id: 295, part: "part5", word: "August", meaning: "8月" },
  { id: 296, part: "part5", word: "September", meaning: "9月" },
  { id: 297, part: "part5", word: "October", meaning: "10月" },
  { id: 298, part: "part5", word: "November", meaning: "11月" },
  { id: 299, part: "part5", word: "December", meaning: "12月" },
  { id: 300, part: "part5", word: "spring", meaning: "春" },
  { id: 301, part: "part5", word: "summer", meaning: "夏" },
  { id: 302, part: "part5", word: "autumn", meaning: "秋" },
  { id: 303, part: "part5", word: "winter", meaning: "冬" },
  { id: 304, part: "part5", word: "morning", meaning: "朝" },
  { id: 305, part: "part5", word: "afternoon", meaning: "昼・午後" },
  { id: 306, part: "part5", word: "evening", meaning: "晩・夕方" },
  { id: 307, part: "part5", word: "night", meaning: "夜" },
  { id: 308, part: "part5", word: "one", meaning: "1" },
  { id: 309, part: "part5", word: "two", meaning: "2" },
  { id: 310, part: "part5", word: "three", meaning: "3" },
  { id: 311, part: "part5", word: "four", meaning: "4" },
  { id: 312, part: "part5", word: "five", meaning: "5" },
  { id: 313, part: "part5", word: "six", meaning: "6" },
  { id: 314, part: "part5", word: "seven", meaning: "7" },
  { id: 315, part: "part5", word: "eight", meaning: "8" },
  { id: 316, part: "part5", word: "nine", meaning: "9" },
  { id: 317, part: "part5", word: "ten", meaning: "10" },
  { id: 318, part: "part5", word: "eleven", meaning: "11" },
  { id: 319, part: "part5", word: "twelve", meaning: "12" },
  { id: 320, part: "part5", word: "thirteen", meaning: "13" },
  { id: 321, part: "part5", word: "fourteen", meaning: "14" },
  { id: 322, part: "part5", word: "fifteen", meaning: "15" },
  { id: 323, part: "part5", word: "twenty", meaning: "20" },
  { id: 324, part: "part5", word: "thirty", meaning: "30" },
  { id: 325, part: "part5", word: "hundred", meaning: "100" },
  { id: 326, part: "part5", word: "first", meaning: "第1の・最初の" },
  { id: 327, part: "part5", word: "second", meaning: "第2の・2番目の" },
  { id: 328, part: "part5", word: "third", meaning: "第3の・3番目の" },
  { id: 329, part: "part5", word: "time", meaning: "時間・回" },
  { id: 330, part: "part5", word: "hour", meaning: "1時間" },
  { id: 331, part: "part5", word: "minute", meaning: "分" },
  { id: 332, part: "part5", word: "second", meaning: "秒" },
  { id: 333, part: "part5", word: "day", meaning: "日・1日" },
  { id: 334, part: "part5", word: "week", meaning: "週" },
  { id: 335, part: "part5", word: "month", meaning: "月" },
  { id: 336, part: "part5", word: "year", meaning: "年" },
  { id: 337, part: "part5", word: "red", meaning: "赤" },
  { id: 338, part: "part5", word: "blue", meaning: "青" },
  { id: 339, part: "part5", word: "yellow", meaning: "黄" },
  { id: 340, part: "part5", word: "green", meaning: "緑" },
  { id: 341, part: "part5", word: "white", meaning: "白" },
  { id: 342, part: "part5", word: "black", meaning: "黒" },
  { id: 343, part: "part5", word: "brown", meaning: "茶色" },
  { id: 344, part: "part5", word: "pink", meaning: "ピンク" },
  { id: 345, part: "part5", word: "color", meaning: "色" },
  { id: 346, part: "part5", word: "japan", meaning: "日本" },
  { id: 347, part: "part5", word: "japanese", meaning: "日本語・日本の" },
  { id: 348, part: "part5", word: "english", meaning: "英語・英語の" },
  { id: 349, part: "part5", word: "america", meaning: "アメリカ" },
  { id: 350, part: "part5", word: "american", meaning: "アメリカの・アメリカ人" },

  // --- Part 6 (351〜420語: 身の回り・科目・スポーツ) ---
  { id: 351, part: "part6", word: "math", meaning: "数学" },
  { id: 352, part: "part6", word: "science", meaning: "理科・科学" },
  { id: 353, part: "part6", word: "music", meaning: "音楽" },
  { id: 354, part: "part6", word: "p.e.", meaning: "体育" },
  { id: 355, part: "part6", word: "art", meaning: "美術・芸術" },
  { id: 356, part: "part6", word: "soccer", meaning: "サッカー" },
  { id: 357, part: "part6", word: "baseball", meaning: "野球" },
  { id: 358, part: "part6", word: "tennis", meaning: "テニス" },
  { id: 359, part: "part6", word: "basketball", meaning: "バスケットボール" },
  { id: 360, part: "part6", word: "volleyball", meaning: "バレーボール" },
  { id: 361, part: "part6", word: "piano", meaning: "ピアノ" },
  { id: 362, part: "part6", word: "guitar", meaning: "ギター" },
  { id: 363, part: "part6", word: "song", meaning: "歌" },
  { id: 364, part: "part6", word: "game", meaning: "試合・ゲーム" },
  { id: 365, part: "part6", word: "team", meaning: "チーム" },
  { id: 366, part: "part6", word: "sport", meaning: "スポーツ" },
  { id: 367, part: "part6", word: "clothes", meaning: "服" },
  { id: 368, part: "part6", word: "shirt", meaning: "シャツ" },
  { id: 369, part: "part6", word: "cap", meaning: "帽子" },
  { id: 370, part: "part6", word: "shoes", meaning: "靴" },
  { id: 371, part: "part6", word: "bag", meaning: "バッグ" },
  { id: 372, part: "part6", word: "watch", meaning: "腕時計" },
  { id: 373, part: "part6", word: "money", meaning: "お金" },
  { id: 374, part: "part6", word: "card", meaning: "カード" },
  { id: 375, part: "part6", word: "letter", meaning: "手紙" },
  { id: 376, part: "part6", word: "email", meaning: "Eメール" },
  { id: 377, part: "part6", word: "paper", meaning: "紙" },
  { id: 378, part: "part6", word: "map", meaning: "地図" },
  { id: 379, part: "part6", word: "ticket", meaning: "チケット" },
  { id: 380, part: "part6", word: "food", meaning: "食べ物" },
  { id: 381, part: "part6", word: "fruit", meaning: "果物" },
  { id: 382, part: "part6", word: "cake", meaning: "ケーキ" },
  { id: 383, part: "part6", word: "egg", meaning: "卵" },
  { id: 384, part: "part6", word: "meat", meaning: "肉" },
  { id: 385, part: "part6", word: "fish", meaning: "魚" },
  { id: 386, part: "part6", word: "lunch", meaning: "昼食" },
  { id: 387, part: "part6", word: "dinner", meaning: "夕食" },
  { id: 388, part: "part6", word: "breakfast", meaning: "朝食" },
  { id: 389, part: "part6", word: "meal", meaning: "食事" },
  { id: 390, part: "part6", word: "animal", meaning: "動物" },
  { id: 391, part: "part6", word: "flower", meaning: "花" },
  { id: 392, part: "part6", word: "tree", meaning: "木" },
  { id: 393, part: "part6", word: "sea", meaning: "海" },
  { id: 394, part: "part6", word: "river", meaning: "川" },
  { id: 395, part: "part6", word: "mountain", meaning: "山" },
  { id: 396, part: "part6", word: "sky", meaning: "空" },
  { id: 397, part: "part6", word: "sun", meaning: "太陽" },
  { id: 398, part: "part6", word: "moon", meaning: "月" },
  { id: 399, part: "part6", word: "star", meaning: "星" },
  { id: 400, part: "part6", word: "rain", meaning: "雨" },
  { id: 401, part: "part6", word: "snow", meaning: "雪" },
  { id: 402, part: "part6", word: "wind", meaning: "風" },
  { id: 403, part: "part6", word: "weather", meaning: "天気" },
  { id: 404, part: "part6", word: "country", meaning: "国・田舎" },
  { id: 405, part: "part6", word: "city", meaning: "都市・街" },
  { id: 406, part: "part6", word: "town", meaning: "町" },
  { id: 407, part: "part6", word: "street", meaning: "通り" },
  { id: 408, part: "part6", word: "place", meaning: "場所" },
  { id: 409, part: "part6", word: "world", meaning: "世界" },
  { id: 410, part: "part6", word: "life", meaning: "生活・生命" },
  { id: 411, part: "part6", word: "thing", meaning: "こと・もの" },
  { id: 412, part: "part6", word: "name", meaning: "名前" },
  { id: 413, part: "part6", word: "number", meaning: "数・番号" },
  { id: 414, part: "part6", word: "way", meaning: "道・方法" },
  { id: 415, part: "part6", word: "part", meaning: "部分" },
  { id: 416, part: "part6", word: "side", meaning: "側" },
  { id: 417, part: "part6", word: "hand", meaning: "手" },
  { id: 418, part: "part6", word: "foot", meaning: "足" },
  { id: 419, part: "part6", word: "eye", meaning: "目" },
  { id: 420, part: "part6", word: "ear", meaning: "耳" },

  // --- Part 7 (421〜490語: 身体・自然・名詞・動詞2) ---
  { id: 421, part: "part7", word: "mouth", meaning: "口" },
  { id: 422, part: "part7", word: "head", meaning: "頭" },
  { id: 423, part: "part7", word: "face", meaning: "顔" },
  { id: 424, part: "part7", word: "hair", meaning: "髪" },
  { id: 425, part: "part7", word: "body", meaning: "体" },
  { id: 426, part: "part7", word: "headache", meaning: "頭痛" },
  { id: 427, part: "part7", word: "fever", meaning: "熱" },
  { id: 428, part: "part7", word: "cold", meaning: "風邪" },
  { id: 429, part: "part7", word: "health", meaning: "健康" },
  { id: 430, part: "part7", word: "party", meaning: "パーティー" },
  { id: 431, part: "part7", word: "event", meaning: "行事・イベント" },
  { id: 432, part: "part7", word: "trip", meaning: "旅行" },
  { id: 433, part: "part7", word: "vacation", meaning: "休み・休暇" },
  { id: 434, part: "part7", word: "holiday", meaning: "祝日・休日" },
  { id: 435, part: "part7", word: "birthday", meaning: "誕生日" },
  { id: 436, part: "part7", word: "present", meaning: "プレゼント" },
  { id: 437, part: "part7", word: "gift", meaning: "贈り物" },
  { id: 438, part: "part7", word: "idea", meaning: "考え・アイデア" },
  { id: 439, part: "part7", word: "problem", meaning: "問題" },
  { id: 440, part: "part7", word: "question", meaning: "質問" },
  { id: 441, part: "part7", word: "answer", meaning: "答え" },
  { id: 442, part: "part7", word: "story", meaning: "物語・お話" },
  { id: 443, part: "part7", word: "word", meaning: "単語・言葉" },
  { id: 444, part: "part7", word: "sentence", meaning: "文" },
  { id: 445, part: "part7", word: "page", meaning: "ページ" },
  { id: 446, part: "part7", word: "line", meaning: "線・列" },
  { id: 447, part: "part7", word: "point", meaning: "点・ポイント" },
  { id: 448, part: "part7", word: "end", meaning: "終わり" },
  { id: 449, part: "part7", word: "top", meaning: "頂上・一番上" },
  { id: 450, part: "part7", word: "bottom", meaning: "底・一番下" },
  { id: 451, part: "part7", word: "open", meaning: "開いている" },
  { id: 452, part: "part7", word: "closed", meaning: "閉まっている" },
  { id: 453, part: "part7", word: "right", meaning: "正しい・右の" },
  { id: 454, part: "part7", word: "wrong", meaning: "間違っている" },
  { id: 455, part: "part7", word: "left", meaning: "左の" },
  { id: 456, part: "part7", word: "true", meaning: "本当の" },
  { id: 457, part: "part7", word: "false", meaning: "偽の" },
  { id: 458, part: "part7", word: "sure", meaning: "確信している" },
  { id: 459, part: "part7", word: "ready", meaning: "準備ができている" },
  { id: 460, part: "part7", word: "free", meaning: "自由な・暇な" },
  { id: 461, part: "part7", word: "quiet", meaning: "静かな" },
  { id: 462, part: "part7", word: "loud", meaning: "うるさい・大声の" },
  { id: 463, part: "part7", word: "soft", meaning: "柔らかい・静かな" },
  { id: 464, part: "part7", word: "hard", meaning: "硬い" },
  { id: 465, part: "part7", word: "full", meaning: "いっぱいの" },
  { id: 466, part: "part7", word: "empty", meaning: "空の" },
  { id: 467, part: "part7", word: "deep", meaning: "深い" },
  { id: 468, part: "part7", word: "shallow", meaning: "浅い" },
  { id: 469, part: "part7", word: "wide", meaning: "広い" },
  { id: 470, part: "part7", word: "narrow", meaning: "狭い" },
  { id: 471, part: "part7", word: "high", meaning: "高い" },
  { id: 472, part: "part7", word: "low", meaning: "低い" },
  { id: 473, part: "part7", word: "same", meaning: "同じ" },
  { id: 474, part: "part7", word: "next", meaning: "次の" },
  { id: 475, part: "part7", word: "last", meaning: "最後の・この前の" },
  { id: 476, part: "part7", word: "first", meaning: "最初の" },
  { id: 477, part: "part7", word: "final", meaning: "最終の" },
  { id: 478, part: "part7", word: "real", meaning: "現実の・本物の" },
  { id: 479, part: "part7", word: "fair", meaning: "公平な" },
  { id: 480, part: "part7", word: "safe", meaning: "安全な" },
  { id: 481, part: "part7", word: "dangerous", meaning: "危険な" },
  { id: 482, part: "part7", word: "rich", meaning: "豊かな" },
  { id: 483, part: "part7", word: "poor", meaning: "貧しい" },
  { id: 484, part: "part7", word: "kind", meaning: "親切な" },
  { id: 485, part: "part7", word: "cruel", meaning: "残酷な" },
  { id: 486, part: "part7", word: "sweet", meaning: "甘い" },
  { id: 487, part: "part7", word: "sour", meaning: "酸っぱい" },
  { id: 488, part: "part7", word: "salty", meaning: "しょっぱい" },
  { id: 489, part: "part7", word: "bitter", meaning: "苦い" },
  { id: 490, part: "part7", word: "spicy", meaning: "辛い" },

  // --- Part 8 (491〜560語: 基本熟語1) ---
  { id: 491, part: "part8", word: "get up", meaning: "起きる" },
  { id: 492, part: "part8", word: "go to bed", meaning: "寝る" },
  { id: 493, part: "part8", word: "come in", meaning: "入る" },
  { id: 494, part: "part8", word: "sit down", meaning: "座る" },
  { id: 495, part: "part8", word: "stand up", meaning: "立つ" },
  { id: 496, part: "part8", word: "look at", meaning: "〜を見る" },
  { id: 497, part: "part8", word: "listen to", meaning: "〜を聴く" },
  { id: 498, part: "part8", word: "after school", meaning: "放課後" },
  { id: 499, part: "part8", word: "of course", meaning: "もちろん" },
  { id: 500, part: "part8", word: "welcome to", meaning: "〜へようこそ" },
  { id: 501, part: "part8", word: "by train", meaning: "電車で" },
  { id: 502, part: "part8", word: "on foot", meaning: "徒歩で" },
  { id: 503, part: "part8", word: "a lot of", meaning: "たくさんの" },
  { id: 504, part: "part8", word: "take a picture", meaning: "写真を撮る" },
  { id: 505, part: "part8", word: "have a good time", meaning: "楽しむ" },
  { id: 506, part: "part8", word: "go shopping", meaning: "買い物に行く" },
  { id: 507, part: "part8", word: "pardon?", meaning: "もう一度言ってください" },
  { id: 508, part: "part8", word: "you're welcome", meaning: "どういたしまして" },
  { id: 509, part: "part8", word: "me, too", meaning: "私もしそうです" },
  { id: 510, part: "part8", word: "here you are", meaning: "はい、どうぞ" },
  { id: 511, part: "part8", word: "see you", meaning: "またね" },
  { id: 512, part: "part8", word: "good morning", meaning: "おはよう" },
  { id: 513, part: "part8", word: "good night", meaning: "おやすみなさい" },
  { id: 514, part: "part8", word: "how are you?", meaning: "お元気ですか" },
  { id: 515, part: "part8", word: "nice to meet you", meaning: "はじめまして" },
  { id: 516, part: "part8", word: "excuse me", meaning: "すみません" },
  { id: 517, part: "part8", word: "i'm sorry", meaning: "ごめんなさい" },
  { id: 518, part: "part8", word: "thank you", meaning: "ありがとう" },
  { id: 519, part: "part8", word: "all right", meaning: "わかりました・大丈夫です" },
  { id: 520, part: "part8", word: "look for", meaning: "〜を探す" },
  { id: 521, part: "part8", word: "take off", meaning: "脱ぐ・離陸する" },
  { id: 522, part: "part8", word: "put on", meaning: "着る・身につける" },
  { id: 523, part: "part8", word: "turn on", meaning: "（電気等を）つける" },
  { id: 524, part: "part8", word: "turn off", meaning: "（電気等を）消す" },
  { id: 525, part: "part8", word: "get in", meaning: "乗り込む" },
  { id: 526, part: "part8", word: "get out", meaning: "外に出る" },
  { id: 527, part: "part8", word: "go out", meaning: "出かける" },
  { id: 528, part: "part8", word: "come back", meaning: "戻る" },
  { id: 529, part: "part8", word: "go back", meaning: "帰る・戻る" },
  { id: 530, part: "part8", word: "run away", meaning: "逃げる" },
  { id: 531, part: "part8", word: "wake up", meaning: "目を覚ます" },
  { id: 532, part: "part8", word: "grow up", meaning: "成長する" },
  { id: 533, part: "part8", word: "clean up", meaning: "掃除する" },
  { id: 534, part: "part8", word: "give up", meaning: "諦める" },
  { id: 535, part: "part8", word: "pick up", meaning: "拾う・車で迎える" },
  { id: 536, part: "part8", word: "wash hands", meaning: "手を洗う" },
  { id: 537, part: "part8", word: "brush teeth", meaning: "歯を磨く" },
  { id: 538, part: "part8", word: "take a bath", meaning: "お風呂に入る" },
  { id: 539, part: "part8", word: "take a walk", meaning: "散歩する" },
  { id: 540, part: "part8", word: "have breakfast", meaning: "朝食を食べる" },
  { id: 541, part: "part8", word: "have lunch", meaning: "昼食を食べる" },
  { id: 542, part: "part8", word: "have dinner", meaning: "夕食を食べる" },
  { id: 543, part: "part8", word: "go to school", meaning: "学校に行く" },
  { id: 544, part: "part8", word: "go home", meaning: "家に帰る" },
  { id: 545, part: "part8", word: "do homework", meaning: "宿題をする" },
  { id: 546, part: "part8", word: "play cards", meaning: "トランプをする" },
  { id: 547, part: "part8", word: "play games", meaning: "ゲームをする" },
  { id: 548, part: "part8", word: "watch tv", meaning: "テレビを見る" },
  { id: 549, part: "part8", word: "read a book", meaning: "本を読む" },
  { id: 550, part: "part8", word: "write a letter", meaning: "手紙を書く" },
  { id: 551, part: "part8", word: "speak english", meaning: "英語を話す" },
  { id: 552, part: "part8", word: "listen to music", meaning: "音楽を聴く" },
  { id: 553, part: "part8", word: "play the piano", meaning: "ピアノを弾く" },
  { id: 554, part: "part8", word: "play the guitar", meaning: "ギターを弾く" },
  { id: 555, part: "part8", word: "ride a bike", meaning: "自転車に乗る" },
  { id: 556, part: "part8", word: "drive a car", meaning: "車を運転する" },
  { id: 557, part: "part8", word: "cook dinner", meaning: "夕食を作る" },
  { id: 558, part: "part8", word: "help mother", meaning: "母を手伝う" },
  { id: 559, part: "part8", word: "clean the room", meaning: "部屋を掃除する" },
  { id: 560, part: "part8", word: "open the door", meaning: "ドアを開ける" },

  // --- Part 9 (561〜630語: 応用連語・対話表現1) ---
  { id: 561, part: "part9", word: "close the window", meaning: "窓を閉める" },
  { id: 562, part: "part9", word: "turn left", meaning: "左に曲がる" },
  { id: 563, part: "part9", word: "turn right", meaning: "右に曲がる" },
  { id: 564, part: "part9", word: "go straight", meaning: "まっすぐ行く" },
  { id: 565, part: "part9", word: "near here", meaning: "この近くに" },
  { id: 566, part: "part9", word: "over there", meaning: "あそこに" },
  { id: 567, part: "part9", word: "this way", meaning: "こちらへ" },
  { id: 568, part: "part9", word: "that's right", meaning: "その通りです" },
  { id: 569, part: "part9", word: "that's fine", meaning: "それでいいです" },
  { id: 570, part: "part9", word: "no problem", meaning: "問題ありません" },
  { id: 571, part: "part9", word: "i see", meaning: "なるほど・わかりました" },
  { id: 572, part: "part9", word: "i think so", meaning: "そう思います" },
  { id: 573, part: "part9", word: "i hope so", meaning: "そうだといいですね" },
  { id: 574, part: "part9", word: "of course not", meaning: "もちろん違います" },
  { id: 575, part: "part9", word: "sounds good", meaning: "いいですね" },
  { id: 576, part: "part9", word: "why not?", meaning: "ぜひやりましょう" },
  { id: 577, part: "part9", word: "how about you?", meaning: "あなたはどうですか" },
  { id: 578, part: "part9", word: "what's up?", meaning: "どうしたの？" },
  { id: 579, part: "part9", word: "what's wrong?", meaning: "どうしましたか？" },
  { id: 580, part: "part9", word: "are you ready?", meaning: "準備はいいですか" },
  { id: 581, part: "part9", word: "are you sure?", meaning: "確かですか" },
  { id: 582, part: "part9", word: "just a moment", meaning: "ちょっと待ってください" },
  { id: 583, part: "part9", word: "wait a minute", meaning: "ちょっと待って" },
  { id: 584, part: "part9", word: "by the way", meaning: "ところで" },
  { id: 585, part: "part9", word: "for example", meaning: "例えば" },
  { id: 586, part: "part9", word: "in fact", meaning: "実際に" },
  { id: 587, part: "part9", word: "at last", meaning: "ついに・ついに" },
  { id: 588, part: "part9", word: "first of all", meaning: "まず第一に" },
  { id: 589, part: "part9", word: "at first", meaning: "最初は" },
  { id: 590, part: "part9", word: "at home", meaning: "家で" },
  { id: 591, part: "part9", word: "at school", meaning: "学校で" },
  { id: 592, part: "part9", word: "at work", meaning: "職場で" },
  { id: 593, part: "part9", word: "in class", meaning: "授業中に" },
  { id: 594, part: "part9", word: "in bed", meaning: "寝ていて" },
  { id: 595, part: "part9", word: "on time", meaning: "時間通りに" },
  { id: 596, part: "part9", word: "in time", meaning: "間に合って" },
  { id: 597, part: "part9", word: "all day", meaning: "一日中" },
  { id: 598, part: "part9", word: "every day", meaning: "毎日" },
  { id: 599, part: "part9", word: "every week", meaning: "毎週" },
  { id: 600, part: "part9", word: "every year", meaning: "毎年" },
  { id: 601, part: "part9", word: "last week", meaning: "先週" },
  { id: 602, part: "part9", word: "next week", meaning: "来週" },
  { id: 603, part: "part9", word: "this morning", meaning: "今朝" },
  { id: 604, part: "part9", word: "tonight", meaning: "今夜" },
  { id: 605, part: "part9", word: "someday", meaning: "いつか" },
  { id: 606, part: "part9", word: "soon", meaning: "すぐに" },
  { id: 607, part: "part9", word: "later", meaning: "後で" },
  { id: 608, part: "part9", word: "ago", meaning: "〜前に" },
  { id: 609, part: "part9", word: "far away", meaning: "遠くに" },
  { id: 610, part: "part9", word: "right now", meaning: "たった今" },
  { id: 611, part: "part9", word: "so much", meaning: "とてもたくさん" },
  { id: 612, part: "part9", word: "too much", meaning: "多すぎる" },
  { id: 613, part: "part9", word: "a few", meaning: "いくつかの" },
  { id: 614, part: "part9", word: "a little", meaning: "少しの" },
  { id: 615, part: "part9", word: "more than", meaning: "〜以上" },
  { id: 616, part: "part9", word: "less than", meaning: "〜未満" },
  { id: 617, part: "part9", word: "each other", meaning: "お互いに" },
  { id: 618, part: "part9", word: "one another", meaning: "お互いに" },
  { id: 619, part: "part9", word: "all of", meaning: "〜のすべて" },
  { id: 620, part: "part9", word: "most of", meaning: "〜の大部分" },
  { id: 621, part: "part9", word: "some of", meaning: "〜の一部" },
  { id: 622, part: "part9", word: "kind of", meaning: "〜の種類・ちょっと" },
  { id: 623, part: "part9", word: "a piece of", meaning: "1つの〜" },
  { id: 624, part: "part9", word: "a cup of", meaning: "カップ1杯の" },
  { id: 625, part: "part9", word: "a glass of", meaning: "コップ1杯の" },
  { id: 626, part: "part9", word: "a pair of", meaning: "1組の" },
  { id: 627, part: "part9", word: "hundreds of", meaning: "何百もの" },
  { id: 628, part: "part9", word: "thousands of", meaning: "何千もの" },
  { id: 629, part: "part9", word: "millions of", meaning: "何百万もの" },
  { id: 630, part: "part9", word: "full of", meaning: "〜でいっぱいの" },

  // --- Part 10 (631〜700語: 応用連語・会話表現2・まとめ) ---
  { id: 631, part: "part10", word: "be good at", meaning: "〜が得意である" },
  { id: 632, part: "part10", word: "be interested in", meaning: "〜に興味がある" },
  { id: 633, part: "part10", word: "be late for", meaning: "〜に遅れる" },
  { id: 634, part: "part10", word: "be ready for", meaning: "〜の準備ができている" },
  { id: 635, part: "part10", word: "be afraid of", meaning: "〜を恐れる" },
  { id: 636, part: "part10", word: "be proud of", meaning: "〜を誇りに思う" },
  { id: 637, part: "part10", word: "be surprised at", meaning: "〜に驚く" },
  { id: 638, part: "part10", word: "be covered with", meaning: "〜で覆われている" },
  { id: 639, part: "part10", word: "be made of", meaning: "〜で作られている" },
  { id: 640, part: "part10", word: "be famous for", meaning: "〜で有名である" },
  { id: 641, part: "part10", word: "look like", meaning: "〜のように見える" },
  { id: 642, part: "part10", word: "sound like", meaning: "〜のように聞こえる" },
  { id: 643, part: "part10", word: "feel like", meaning: "〜したい気がする" },
  { id: 644, part: "part10", word: "take care of", meaning: "〜の世話をする" },
  { id: 645, part: "part10", word: "look forward to", meaning: "〜を楽しみに待つ" },
  { id: 646, part: "part10", word: "make friends with", meaning: "〜と友達になる" },
  { id: 647, part: "part10", word: "shake hands", meaning: "握手する" },
  { id: 648, part: "part10", word: "change mind", meaning: "考えを変える" },
  { id: 649, part: "part10", word: "keep a secret", meaning: "秘密を守る" },
  { id: 650, part: "part10", word: "tell a lie", meaning: "嘘をつく" },
  { id: 651, part: "part10", word: "tell the truth", meaning: "真実を話す" },
  { id: 652, part: "part10", word: "say hello to", meaning: "〜によろしく言う" },
  { id: 653, part: "part10", word: "give a hand", meaning: "手を貸す" },
  { id: 654, part: "part10", word: "have a cold", meaning: "風邪をひいている" },
  { id: 655, part: "part10", word: "catch a cold", meaning: "風邪をひく" },
  { id: 656, part: "part10", word: "stay in bed", meaning: "寝ている" },
  { id: 657, part: "part10", word: "take medicine", meaning: "薬を飲む" },
  { id: 658, part: "part10", word: "go on a picnic", meaning: "ピクニックに行く" },
  { id: 659, part: "part10", word: "go on a trip", meaning: "旅行に行く" },
  { id: 660, part: "part10", word: "have a party", meaning: "パーティーを開く" },
  { id: 661, part: "part10", word: "enjoy oneself", meaning: "楽しむ" },
  { id: 662, part: "part10", word: "help oneself", meaning: "自由に取って食べる" },
  { id: 663, part: "part10", word: "by oneself", meaning: "1人で" },
  { id: 664, part: "part10", word: "say to oneself", meaning: "心の中でつぶやく" },
  { id: 665, part: "part10", word: "so that", meaning: "〜するために" },
  { id: 666, part: "part10", word: "too to", meaning: "あまりに〜なので…できない" },
  { id: 667, part: "part10", word: "either or", meaning: "〜か…のどちらか" },
  { id: 668, part: "part10", word: "neither nor", meaning: "〜も…もどちらもない" },
  { id: 669, part: "part10", word: "both and", meaning: "〜も…も両方" },
  { id: 670, part: "part10", word: "not only but also", meaning: "〜だけでなく…も" },
  { id: 671, part: "part10", word: "as soon as", meaning: "〜するとすぐに" },
  { id: 672, part: "part10", word: "as long as", meaning: "〜する限りは" },
  { id: 673, part: "part10", word: "as well as", meaning: "〜と同様に" },
  { id: 674, part: "part10", word: "so as to", meaning: "〜するために" },
  { id: 675, part: "part10", word: "in order to", meaning: "〜するために" },
  { id: 676, part: "part10", word: "according to", meaning: "〜によれば" },
  { id: 677, part: "part10", word: "because of", meaning: "〜のために（原因）" },
  { id: 678, part: "part10", word: "thanks to", meaning: "〜のおかげで" },
  { id: 679, part: "part10", word: "instead of", meaning: "〜の代わりに" },
  { id: 680, part: "part10", word: "in front of", meaning: "〜の正面に" },
  { id: 681, part: "part10", word: "next to", meaning: "〜の隣に" },
  { id: 682, part: "part10", word: "far from", meaning: "〜から遠く離れて" },
  { id: 683, part: "part10", word: "close to", meaning: "〜の近くに" },
  { id: 684, part: "part10", word: "all over", meaning: "〜一面に" },
  { id: 685, part: "part10", word: "around the world", meaning: "世界中で" },
  { id: 686, part: "part10", word: "in the future", meaning: "将来に" },
  { id: 687, part: "part10", word: "in the past", meaning: "過去に" },
  { id: 688, part: "part10", word: "at the same time", meaning: "同時に" },
  { id: 689, part: "part10", word: "from now on", meaning: "今からは" },
  { id: 690, part: "part10", word: "once again", meaning: "もう一度" },
  { id: 691, part: "part10", word: "once more", meaning: "もう一度" },
  { id: 692, part: "part10", word: "little by little", meaning: "少しずつ" },
  { id: 693, part: "part10", word: "step by step", meaning: "一歩ずつ" },
  { id: 694, part: "part10", word: "day by day", meaning: "日々" },
  { id: 695, part: "part10", word: "all the time", meaning: "常に" },
  { id: 696, part: "part10", word: "at any time", meaning: "いつでも" },
  { id: 697, part: "part10", word: "in a word", meaning: "一言で言えば" },
  { id: 698, part: "part10", word: "to tell the truth", meaning: "実を言うと" },
  { id: 699, part: "part10", word: "best wishes", meaning: "ご多幸を祈って" },
  { id: 700, part: "part10", word: "good luck", meaning: "幸運を祈る" }
];
