const wordsData = {
  "5": [
    // --- ① 日時・カレンダー (1_date) ---
    { id: 1, part: "1_date", word: "Sunday", meaning: "日曜日" },
    { id: 2, part: "1_date", word: "Monday", meaning: "月曜日" },
    { id: 3, part: "1_date", word: "Tuesday", meaning: "火曜日" },
    { id: 4, part: "1_date", word: "Wednesday", meaning: "水曜日" },
    { id: 5, part: "1_date", word: "Thursday", meaning: "木曜日" },
    { id: 6, part: "1_date", word: "Friday", meaning: "金曜日" },
    { id: 7, part: "1_date", word: "Saturday", meaning: "土曜日" },
    { id: 8, part: "1_date", word: "January", meaning: "1月" },
    { id: 9, part: "1_date", word: "February", meaning: "2月" },
    { id: 10, part: "1_date", word: "March", meaning: "3月" },
    { id: 11, part: "1_date", word: "April", meaning: "4月" },
    { id: 12, part: "1_date", word: "May", meaning: "5月" },
    { id: 13, part: "1_date", word: "June", meaning: "6月" },
    { id: 14, part: "1_date", word: "July", meaning: "7月" },
    { id: 15, part: "1_date", word: "August", meaning: "8月" },
    { id: 16, part: "1_date", word: "September", meaning: "9月" },
    { id: 17, part: "1_date", word: "October", meaning: "10月" },
    { id: 18, part: "1_date", word: "November", meaning: "11月" },
    { id: 19, part: "1_date", word: "December", meaning: "12月" },
    { id: 20, part: "1_date", word: "spring", meaning: "春" },
    { id: 21, part: "1_date", word: "summer", meaning: "夏" },
    { id: 22, part: "1_date", word: "autumn", meaning: "秋" },
    { id: 23, part: "1_date", word: "winter", meaning: "冬" },
    { id: 24, part: "1_date", word: "morning", meaning: "朝" },
    { id: 25, part: "1_date", word: "afternoon", meaning: "昼・午後" },
    { id: 26, part: "1_date", word: "evening", meaning: "晩・夕方" },
    { id: 27, part: "1_date", word: "night", meaning: "夜" },
    { id: 28, part: "1_date", word: "today", meaning: "今日" },
    { id: 29, part: "1_date", word: "tomorrow", meaning: "明日" },
    { id: 30, part: "1_date", word: "yesterday", meaning: "昨日" },
    { id: 31, part: "1_date", word: "now", meaning: "今" },
    { id: 32, part: "1_date", word: "time", meaning: "時間・回" },
    { id: 33, part: "1_date", word: "hour", meaning: "1時間" },
    { id: 34, part: "1_date", word: "minute", meaning: "分" },
    { id: 35, part: "1_date", word: "second", meaning: "秒" },
    { id: 36, part: "1_date", word: "day", meaning: "日・1日" },
    { id: 37, part: "1_date", word: "week", meaning: "週" },
    { id: 38, part: "1_date", word: "month", meaning: "月" },
    { id: 39, part: "1_date", word: "year", meaning: "年" },
    { id: 40, part: "1_date", word: "early", meaning: "早く" },
    { id: 41, part: "1_date", word: "late", meaning: "遅く" },

    // --- ② 数・色・基本 (2_num_color) ---
    { id: 42, part: "2_num_color", word: "one", meaning: "1" },
    { id: 43, part: "2_num_color", word: "two", meaning: "2" },
    { id: 44, part: "2_num_color", word: "three", meaning: "3" },
    { id: 45, part: "2_num_color", word: "four", meaning: "4" },
    { id: 46, part: "2_num_color", word: "five", meaning: "5" },
    { id: 47, part: "2_num_color", word: "six", meaning: "6" },
    { id: 48, part: "2_num_color", word: "seven", meaning: "7" },
    { id: 49, part: "2_num_color", word: "eight", meaning: "8" },
    { id: 50, part: "2_num_color", word: "nine", meaning: "9" },
    { id: 51, part: "2_num_color", word: "ten", meaning: "10" },
    { id: 52, part: "2_num_color", word: "eleven", meaning: "11" },
    { id: 53, part: "2_num_color", word: "twelve", meaning: "12" },
    { id: 54, part: "2_num_color", word: "thirteen", meaning: "13" },
    { id: 55, part: "2_num_color", word: "fourteen", meaning: "14" },
    { id: 56, part: "2_num_color", word: "fifteen", meaning: "15" },
    { id: 57, part: "2_num_color", word: "twenty", meaning: "20" },
    { id: 58, part: "2_num_color", word: "thirty", meaning: "30" },
    { id: 59, part: "2_num_color", word: "hundred", meaning: "100" },
    { id: 60, part: "2_num_color", word: "first", meaning: "第1の・最初の" },
    { id: 61, part: "2_num_color", word: "second", meaning: "第2の・2番目の" },
    { id: 62, part: "2_num_color", word: "third", meaning: "第3の・3番目の" },
    { id: 63, part: "2_num_color", word: "red", meaning: "赤" },
    { id: 64, part: "2_num_color", word: "blue", meaning: "青" },
    { id: 65, part: "2_num_color", word: "yellow", meaning: "黄" },
    { id: 66, part: "2_num_color", word: "green", meaning: "緑" },
    { id: 67, part: "2_num_color", word: "white", meaning: "白" },
    { id: 68, part: "2_num_color", word: "black", meaning: "黒" },
    { id: 69, part: "2_num_color", word: "brown", meaning: "茶色" },
    { id: 70, part: "2_num_color", word: "pink", meaning: "ピンク" },
    { id: 71, part: "2_num_color", word: "color", meaning: "色" },
    { id: 72, part: "2_num_color", word: "Japan", meaning: "日本" },
    { id: 73, part: "2_num_color", word: "Japanese", meaning: "日本語・日本の" },
    { id: 74, part: "2_num_color", word: "English", meaning: "英語・英語の" },
    { id: 75, part: "2_num_color", word: "America", meaning: "アメリカ" },
    { id: 76, part: "2_num_color", word: "American", meaning: "アメリカの・アメリカ人" },

    // --- ③ 身の回り・学校 (3_school_sports) ---
    { id: 77, part: "3_school_sports", word: "book", meaning: "本" },
    { id: 78, part: "3_school_sports", word: "pen", meaning: "ペン" },
    { id: 79, part: "3_school_sports", word: "pencil", meaning: "鉛筆" },
    { id: 80, part: "3_school_sports", word: "desk", meaning: "つくえ" },
    { id: 81, part: "3_school_sports", word: "chair", meaning: "いす" },
    { id: 82, part: "3_school_sports", word: "bag", meaning: "かばん" },
    { id: 83, part: "3_school_sports", word: "notebook", meaning: "ノート" },
    { id: 84, part: "3_school_sports", word: "box", meaning: "箱" },
    { id: 85, part: "3_school_sports", word: "clock", meaning: "時計" },
    { id: 86, part: "3_school_sports", word: "picture", meaning: "写真・絵" },
    { id: 87, part: "3_school_sports", word: "computer", meaning: "コンピュータ" },
    { id: 88, part: "3_school_sports", word: "phone", meaning: "電話" },
    { id: 89, part: "3_school_sports", word: "school", meaning: "学校" },
    { id: 90, part: "3_school_sports", word: "classroom", meaning: "教室" },
    { id: 91, part: "3_school_sports", word: "teacher", meaning: "先生" },
    { id: 92, part: "3_school_sports", word: "student", meaning: "生徒" },
    { id: 93, part: "3_school_sports", word: "class", meaning: "授業・クラス" },
    { id: 94, part: "3_school_sports", word: "homework", meaning: "宿題" },
    { id: 95, part: "3_school_sports", word: "test", meaning: "テスト" },
    { id: 96, part: "3_school_sports", word: "math", meaning: "数学" },
    { id: 97, part: "3_school_sports", word: "science", meaning: "理科・科学" },
    { id: 98, part: "3_school_sports", word: "music", meaning: "音楽" },
    { id: 99, part: "3_school_sports", word: "P.E.", meaning: "体育" },
    { id: 100, part: "3_school_sports", word: "art", meaning: "美術・芸術" },
    { id: 101, part: "3_school_sports", word: "soccer", meaning: "サッカー" },
    { id: 102, part: "3_school_sports", word: "baseball", meaning: "野球" },
    { id: 103, part: "3_school_sports", word: "tennis", meaning: "テニス" },
    { id: 104, part: "3_school_sports", word: "basketball", meaning: "バスケットボール" },
    { id: 105, part: "3_school_sports", word: "volleyball", meaning: "バレーボール" },
    { id: 106, part: "3_school_sports", word: "piano", meaning: "ピアノ" },
    { id: 107, part: "3_school_sports", word: "guitar", meaning: "ギター" },
    { id: 108, part: "3_school_sports", word: "song", meaning: "歌" },
    { id: 109, part: "3_school_sports", word: "game", meaning: "試合・ゲーム" },
    { id: 110, part: "3_school_sports", word: "team", meaning: "チーム" },
    { id: 111, part: "3_school_sports", word: "sport", meaning: "スポーツ" },

    // --- ④ 家族・人・体 (4_family_body) ---
    { id: 112, part: "4_family_body", word: "father", meaning: "お父さん" },
    { id: 113, part: "4_family_body", word: "mother", meaning: "お母さん" },
    { id: 114, part: "4_family_body", word: "parent", meaning: "親" },
    { id: 115, part: "4_family_body", word: "brother", meaning: "兄弟（兄・弟）" },
    { id: 116, part: "4_family_body", word: "sister", meaning: "姉妹（姉・妹）" },
    { id: 117, part: "4_family_body", word: "son", meaning: "息子" },
    { id: 118, part: "4_family_body", word: "daughter", meaning: "娘" },
    { id: 119, part: "4_family_body", word: "family", meaning: "家族" },
    { id: 120, part: "4_family_body", word: "man", meaning: "男性" },
    { id: 121, part: "4_family_body", word: "woman", meaning: "女性" },
    { id: 122, part: "4_family_body", word: "boy", meaning: "男の子" },
    { id: 123, part: "4_family_body", word: "girl", meaning: "女の子" },
    { id: 124, part: "4_family_body", word: "baby", meaning: "赤ん坊" },
    { id: 125, part: "4_family_body", word: "child", meaning: "子供" },
    { id: 126, part: "4_family_body", word: "friend", meaning: "友達" },
    { id: 127, part: "4_family_body", word: "hand", meaning: "手" },
    { id: 128, part: "4_family_body", word: "foot", meaning: "足" },
    { id: 129, part: "4_family_body", word: "eye", meaning: "目" },
    { id: 130, part: "4_family_body", word: "ear", meaning: "耳" },
    { id: 131, part: "4_family_body", word: "mouth", meaning: "口" },
    { id: 132, part: "4_family_body", word: "head", meaning: "頭" },
    { id: 133, part: "4_family_body", word: "face", meaning: "顔" },
    { id: 134, part: "4_family_body", word: "hair", meaning: "髪" },
    { id: 135, part: "4_family_body", word: "body", meaning: "体" },

    // --- ⑤ 食べ物・生き物・自然 (5_food_nature) ---
    { id: 136, part: "5_food_nature", word: "apple", meaning: "りんご" },
    { id: 137, part: "5_food_nature", word: "banana", meaning: "バナナ" },
    { id: 138, part: "5_food_nature", word: "orange", meaning: "オレンジ" },
    { id: 139, part: "5_food_nature", word: "water", meaning: "水" },
    { id: 140, part: "5_food_nature", word: "milk", meaning: "牛乳" },
    { id: 141, part: "5_food_nature", word: "tea", meaning: "お茶・紅茶" },
    { id: 142, part: "5_food_nature", word: "juice", meaning: "ジュース" },
    { id: 143, part: "5_food_nature", word: "coffee", meaning: "コーヒー" },
    { id: 144, part: "5_food_nature", word: "bread", meaning: "パン" },
    { id: 145, part: "5_food_nature", word: "rice", meaning: "ご飯・米" },
    { id: 146, part: "5_food_nature", word: "food", meaning: "食べ物" },
    { id: 147, part: "5_food_nature", word: "fruit", meaning: "果物" },
    { id: 148, part: "5_food_nature", word: "cake", meaning: "ケーキ" },
    { id: 149, part: "5_food_nature", word: "egg", meaning: "卵" },
    { id: 150, part: "5_food_nature", word: "meat", meaning: "肉" },
    { id: 151, part: "5_food_nature", word: "dog", meaning: "犬" },
    { id: 152, part: "5_food_nature", word: "cat", meaning: "猫" },
    { id: 153, part: "5_food_nature", word: "bird", meaning: "鳥" },
    { id: 154, part: "5_food_nature", word: "fish", meaning: "魚" },
    { id: 155, part: "5_food_nature", word: "bear", meaning: "クマ" },
    { id: 156, part: "5_food_nature", word: "rabbit", meaning: "ウサギ" },
    { id: 157, part: "5_food_nature", word: "animal", meaning: "動物" },
    { id: 158, part: "5_food_nature", word: "flower", meaning: "花" },
    { id: 159, part: "5_food_nature", word: "tree", meaning: "木" },
    { id: 160, part: "5_food_nature", word: "sea", meaning: "海" },
    { id: 161, part: "5_food_nature", word: "river", meaning: "川" },
    { id: 162, part: "5_food_nature", word: "mountain", meaning: "山" },
    { id: 163, part: "5_food_nature", word: "sky", meaning: "空" },
    { id: 164, part: "5_food_nature", word: "sun", meaning: "太陽" },
    { id: 165, part: "5_food_nature", word: "moon", meaning: "月" },
    { id: 166, part: "5_food_nature", word: "star", meaning: "星" },
    { id: 167, part: "5_food_nature", word: "rain", meaning: "雨" },
    { id: 168, part: "5_food_nature", word: "snow", meaning: "雪" },
    { id: 169, part: "5_food_nature", word: "wind", meaning: "風" },
    { id: 170, part: "5_food_nature", word: "weather", meaning: "天気" },

    // --- ⑥ 建物・場所・乗り物 (6_places_town) ---
    { id: 171, part: "6_places_town", word: "house", meaning: "家" },
    { id: 172, part: "6_places_town", word: "home", meaning: "家庭・家へ" },
    { id: 173, part: "6_places_town", word: "room", meaning: "部屋" },
    { id: 174, part: "6_places_town", word: "door", meaning: "ドア" },
    { id: 175, part: "6_places_town", word: "window", meaning: "窓" },
    { id: 176, part: "6_places_town", word: "table", meaning: "テーブル" },
    { id: 177, part: "6_places_town", word: "bed", meaning: "ベッド" },
    { id: 178, part: "6_places_town", word: "kitchen", meaning: "台所" },
    { id: 179, part: "6_places_town", word: "park", meaning: "公園" },
    { id: 180, part: "6_places_town", word: "station", meaning: "駅" },
    { id: 181, part: "6_places_town", word: "shop", meaning: "店" },
    { id: 182, part: "6_places_town", word: "store", meaning: "店" },
    { id: 183, part: "6_places_town", word: "hospital", meaning: "病院" },
    { id: 184, part: "6_places_town", word: "library", meaning: "図書館" },
    { id: 185, part: "6_places_town", word: "bus", meaning: "バス" },
    { id: 186, part: "6_places_town", word: "car", meaning: "車" },
    { id: 187, part: "6_places_town", word: "train", meaning: "電車" },
    { id: 188, part: "6_places_town", word: "bike", meaning: "自転車" },
    { id: 189, part: "6_places_town", word: "plane", meaning: "飛行機" },
    { id: 190, part: "6_places_town", word: "taxi", meaning: "タクシー" },
    { id: 191, part: "6_places_town", word: "country", meaning: "国・田舎" },
    { id: 192, part: "6_places_town", word: "city", meaning: "都市・街" },
    { id: 193, part: "6_places_town", word: "town", meaning: "町" },
    { id: 194, part: "6_places_town", word: "street", meaning: "通り" },
    { id: 195, part: "6_places_town", word: "place", meaning: "場所" },
    { id: 196, part: "6_places_town", word: "world", meaning: "世界" },

    // --- ⑦ 基本の動作（動詞） (7_verbs) ---
    { id: 197, part: "7_verbs", word: "go", meaning: "行く" },
    { id: 198, part: "7_verbs", word: "come", meaning: "来る" },
    { id: 199, part: "7_verbs", word: "see", meaning: "見る・会う" },
    { id: 200, part: "7_verbs", word: "look", meaning: "見る" },
    { id: 201, part: "7_verbs", word: "listen", meaning: "聴く" },
    { id: 202, part: "7_verbs", word: "hear", meaning: "聞こえる" },
    { id: 203, part: "7_verbs", word: "speak", meaning: "話す" },
    { id: 204, part: "7_verbs", word: "talk", meaning: "話す・しゃべる" },
    { id: 205, part: "7_verbs", word: "say", meaning: "言う" },
    { id: 206, part: "7_verbs", word: "eat", meaning: "食べる" },
    { id: 207, part: "7_verbs", word: "drink", meaning: "飲む" },
    { id: 208, part: "7_verbs", word: "read", meaning: "読む" },
    { id: 209, part: "7_verbs", word: "write", meaning: "書く" },
    { id: 210, part: "7_verbs", word: "study", meaning: "勉強する" },
    { id: 211, part: "7_verbs", word: "play", meaning: "遊ぶ・(スポーツを)する" },
    { id: 212, part: "7_verbs", word: "run", meaning: "走る" },
    { id: 213, part: "7_verbs", word: "walk", meaning: "歩く" },
    { id: 214, part: "7_verbs", word: "swim", meaning: "泳ぐ" },
    { id: 215, part: "7_verbs", word: "sing", meaning: "歌う" },
    { id: 216, part: "7_verbs", word: "dance", meaning: "踊る" },
    { id: 217, part: "7_verbs", word: "use", meaning: "使う" },
    { id: 218, part: "7_verbs", word: "make", meaning: "作る" },
    { id: 219, part: "7_verbs", word: "cook", meaning: "料理する" },
    { id: 220, part: "7_verbs", word: "buy", meaning: "買う" },
    { id: 221, part: "7_verbs", word: "help", meaning: "手伝う・助ける" },
    { id: 222, part: "7_verbs", word: "like", meaning: "好む・好き" },
    { id: 223, part: "7_verbs", word: "want", meaning: "欲しい" },
    { id: 224, part: "7_verbs", word: "know", meaning: "知っている" },
    { id: 225, part: "7_verbs", word: "think", meaning: "考える・思う" },
    { id: 226, part: "7_verbs", word: "clean", meaning: "掃除する" },
    { id: 227, part: "7_verbs", word: "wash", meaning: "洗う" },
    { id: 228, part: "7_verbs", word: "open", meaning: "開ける" },
    { id: 229, part: "7_verbs", word: "close", meaning: "閉める" },
    { id: 230, part: "7_verbs", word: "start", meaning: "始まる・始める" },
    { id: 231, part: "7_verbs", word: "stop", meaning: "止まる・止める" },
    { id: 232, part: "7_verbs", word: "live", meaning: "住んでいる" },
    { id: 233, part: "7_verbs", word: "work", meaning: "働く" },
    { id: 234, part: "7_verbs", word: "have", meaning: "持っている・食べる" },
    { id: 235, part: "7_verbs", word: "take", meaning: "連れて行く・撮る" },
    { id: 236, part: "7_verbs", word: "get", meaning: "得られる・手に入れる" },
    { id: 237, part: "7_verbs", word: "give", meaning: "与える・あげる" },
    { id: 238, part: "7_verbs", word: "find", meaning: "見つける" },
    { id: 239, part: "7_verbs", word: "ask", meaning: "尋ねる・頼む" },
    { id: 240, part: "7_verbs", word: "tell", meaning: "話す・教える" },
    { id: 241, part: "7_verbs", word: "teach", meaning: "教える" },
    { id: 242, part: "7_verbs", word: "learn", meaning: "学ぶ" },

    // --- ⑧ 気持ち・状態（形容詞・副詞） (8_adjectives) ---
    { id: 243, part: "8_adjectives", word: "big", meaning: "大きい" },
    { id: 244, part: "8_adjectives", word: "small", meaning: "小さい" },
    { id: 245, part: "8_adjectives", word: "good", meaning: "良い" },
    { id: 246, part: "8_adjectives", word: "bad", meaning: "悪い" },
    { id: 247, part: "8_adjectives", word: "new", meaning: "新しい" },
    { id: 248, part: "8_adjectives", word: "old", meaning: "古い・年をとった" },
    { id: 249, part: "8_adjectives", word: "happy", meaning: "幸せな・嬉しい" },
    { id: 250, part: "8_adjectives", word: "sad", meaning: "悲しい" },
    { id: 251, part: "8_adjectives", word: "hot", meaning: "熱い・暑い" },
    { id: 252, part: "8_adjectives", word: "cold", meaning: "冷たい・寒い" },
    { id: 253, part: "8_adjectives", word: "warm", meaning: "暖かい" },
    { id: 254, part: "8_adjectives", word: "cool", meaning: "涼しい・かっこいい" },
    { id: 255, part: "8_adjectives", word: "high", meaning: "高い" },
    { id: 256, part: "8_adjectives", word: "low", meaning: "低い" },
    { id: 257, part: "8_adjectives", word: "long", meaning: "長い" },
    { id: 258, part: "8_adjectives", word: "short", meaning: "短い・背が低い" },
    { id: 259, part: "8_adjectives", word: "fast", meaning: "速い" },
    { id: 260, part: "8_adjectives", word: "slow", meaning: "遅い" },
    { id: 261, part: "8_adjectives", word: "busy", meaning: "忙しい" },
    { id: 262, part: "8_adjectives", word: "kind", meaning: "親切な" },
    { id: 263, part: "8_adjectives", word: "nice", meaning: "良い・素晴らしい" },
    { id: 264, part: "8_adjectives", word: "fine", meaning: "元気な・良い" },
    { id: 265, part: "8_adjectives", word: "glad", meaning: "嬉しい" },
    { id: 266, part: "8_adjectives", word: "easy", meaning: "簡単な" },
    { id: 267, part: "8_adjectives", word: "hard", meaning: "難しい・硬い" },
    { id: 268, part: "8_adjectives", word: "beautiful", meaning: "美しい" },
    { id: 269, part: "8_adjectives", word: "cute", meaning: "かわいい" },
    { id: 270, part: "8_adjectives", word: "hungry", meaning: "空腹の" },
    { id: 271, part: "8_adjectives", word: "thirsty", meaning: "のどが渇いた" },
    { id: 272, part: "8_adjectives", word: "tired", meaning: "疲れた" },
    { id: 273, part: "8_adjectives", word: "sick", meaning: "病気の" },
    { id: 274, part: "8_adjectives", word: "always", meaning: "いつも" },
    { id: 275, part: "8_adjectives", word: "usually", meaning: "たいてい" },
    { id: 276, part: "8_adjectives", word: "often", meaning: "よく・しばしば" },
    { id: 277, part: "8_adjectives", word: "sometimes", meaning: "ときどき" },
    { id: 278, part: "8_adjectives", word: "very", meaning: "とても" },

    // --- ⑨ 代名詞・疑問詞・つなぎ言葉 (9_pronouns) ---
    { id: 279, part: "9_pronouns", word: "I", meaning: "私は" },
    { id: 280, part: "9_pronouns", word: "my", meaning: "私の" },
    { id: 281, part: "9_pronouns", word: "me", meaning: "私を・私に" },
    { id: 282, part: "9_pronouns", word: "mine", meaning: "私のもの" },
    { id: 283, part: "9_pronouns", word: "you", meaning: "あなたは" },
    { id: 284, part: "9_pronouns", word: "your", meaning: "あなたの" },
    { id: 285, part: "9_pronouns", word: "yours", meaning: "あなたのもの" },
    { id: 286, part: "9_pronouns", word: "he", meaning: "彼は" },
    { id: 287, part: "9_pronouns", word: "his", meaning: "彼の・彼のもの" },
    { id: 288, part: "9_pronouns", word: "him", meaning: "彼を・彼に" },
    { id: 289, part: "9_pronouns", word: "she", meaning: "彼女は" },
    { id: 290, part: "9_pronouns", word: "her", meaning: "彼女の・彼女を" },
    { id: 291, part: "9_pronouns", word: "we", meaning: "私たちは" },
    { id: 292, part: "9_pronouns", word: "our", meaning: "私たちの" },
    { id: 293, part: "9_pronouns", word: "us", meaning: "私達を・私達に" },
    { id: 294, part: "9_pronouns", word: "they", meaning: "彼らは・それらは" },
    { id: 295, part: "9_pronouns", word: "their", meaning: "彼らの・それらの" },
    { id: 296, part: "9_pronouns", word: "them", meaning: "彼らを・それらを" },
    { id: 297, part: "9_pronouns", word: "this", meaning: "これ・この" },
    { id: 298, part: "9_pronouns", word: "that", meaning: "あれ・あの" },
    { id: 299, part: "9_pronouns", word: "what", meaning: "何" },
    { id: 300, part: "9_pronouns", word: "who", meaning: "誰" },
    { id: 301, part: "9_pronouns", word: "where", meaning: "どこ" },
    { id: 302, part: "9_pronouns", word: "when", meaning: "いつ" },
    { id: 303, part: "9_pronouns", word: "why", meaning: "なぜ" },
    { id: 304, part: "9_pronouns", word: "how", meaning: "どのように" },
    { id: 305, part: "9_pronouns", word: "which", meaning: "どちら" },
    { id: 306, part: "9_pronouns", word: "and", meaning: "〜と・そして" },
    { id: 307, part: "9_pronouns", word: "but", meaning: "しかし" },
    { id: 308, part: "9_pronouns", word: "or", meaning: "または" },
    { id: 309, part: "9_pronouns", word: "in", meaning: "〜の中に" },
    { id: 310, part: "9_pronouns", word: "on", meaning: "〜の上に" },
    { id: 311, part: "9_pronouns", word: "under", meaning: "〜の下に" },
    { id: 312, part: "9_pronouns", word: "at", meaning: "〜で" },
    { id: 313, part: "9_pronouns", word: "to", meaning: "〜へ・〜に" },
    { id: 314, part: "9_pronouns", word: "from", meaning: "〜から" },
    { id: 315, part: "9_pronouns", word: "with", meaning: "〜と一緒に" },

    // --- ⑩ あいさつ・基本熟語 (10_phrases) ---
    { id: 316, part: "10_phrases", word: "get up", meaning: "起きる" },
    { id: 317, part: "10_phrases", word: "go to bed", meaning: "寝る" },
    { id: 318, part: "10_phrases", word: "come in", meaning: "入る" },
    { id: 319, part: "10_phrases", word: "sit down", meaning: "座る" },
    { id: 320, part: "10_phrases", word: "stand up", meaning: "立つ" },
    { id: 321, part: "10_phrases", word: "look at", meaning: "〜を見る" },
    { id: 322, part: "10_phrases", word: "listen to", meaning: "〜を聴く" },
    { id: 323, part: "10_phrases", word: "after school", meaning: "放課後" },
    { id: 324, part: "10_phrases", word: "of course", meaning: "もちろん" },
    { id: 325, part: "10_phrases", word: "welcome to", meaning: "〜へようこそ" },
    { id: 326, part: "10_phrases", word: "a lot of", meaning: "たくさんの" },
    { id: 327, part: "10_phrases", word: "take a picture", meaning: "写真を撮る" },
    { id: 328, part: "10_phrases", word: "have a good time", meaning: "楽しむ" },
    { id: 329, part: "10_phrases", word: "you're welcome", meaning: "どういたしまして" },
    { id: 330, part: "10_phrases", word: "here you are", meaning: "はい、どうぞ" },
    { id: 331, part: "10_phrases", word: "good morning", meaning: "おはよう" },
    { id: 332, part: "10_phrases", word: "good night", meaning: "おやすみなさい" },
    { id: 333, part: "10_phrases", word: "how are you?", meaning: "お元気ですか" },
    { id: 334, part: "10_phrases", word: "nice to meet you", meaning: "はじめまして" },
    { id: 335, part: "10_phrases", word: "excuse me", meaning: "すみません" },
    { id: 336, part: "10_phrases", word: "thank you", meaning: "ありがとう" },
    { id: 337, part: "10_phrases", word: "take a walk", meaning: "散歩する" },
    { id: 338, part: "10_phrases", word: "go home", meaning: "家に帰る" },
    { id: 339, part: "10_phrases", word: "watch TV", meaning: "テレビを見る" }
  ],
  "4": [
    // --- ① 学校・学習・情報 (1_study_info) ---
    { id: 1001, part: "1_study_info", word: "dictionary", meaning: "辞書" },
    { id: 1002, part: "1_study_info", word: "subject", meaning: "教科・科目" },
    { id: 1003, part: "1_study_info", word: "history", meaning: "歴史" },
    { id: 1004, part: "1_study_info", word: "language", meaning: "言語・言葉" },
    { id: 1005, part: "1_study_info", word: "schedule", meaning: "予定・スケジュール" },
    { id: 1006, part: "1_study_info", word: "meaning", meaning: "意味" },
    { id: 1007, part: "1_study_info", word: "fact", meaning: "事実" },
    { id: 1008, part: "1_study_info", word: "news", meaning: "ニュース・知らせ" },
    { id: 1009, part: "1_study_info", word: "information", meaning: "情報" },
    { id: 1010, part: "1_study_info", word: "program", meaning: "番組・プログラム" },
    { id: 1011, part: "1_study_info", word: "internet", meaning: "インターネット" },
    { id: 1012, part: "1_study_info", word: "website", meaning: "ウェブサイト" },
    { id: 1013, part: "1_study_info", word: "message", meaning: "伝言・メッセージ" },
    { id: 1014, part: "1_study_info", word: "video", meaning: "動画・ビデオ" },

    // --- ② 街・施設・交通 (2_town_places) ---
    { id: 1015, part: "2_town_places", word: "office", meaning: "事務所・オフィス" },
    { id: 1016, part: "2_town_places", word: "factory", meaning: "工場" },
    { id: 1017, part: "2_town_places", word: "museum", meaning: "博物館・美術館" },
    { id: 1018, part: "2_town_places", word: "stadium", meaning: "競技場・スタジアム" },
    { id: 1019, part: "2_town_places", word: "airport", meaning: "空港" },
    { id: 1020, part: "2_town_places", word: "building", meaning: "建物・ビル" },
    { id: 1021, part: "2_town_places", word: "corner", meaning: "角・コーナー" },
    { id: 1022, part: "2_town_places", word: "bridge", meaning: "橋" },
    { id: 1023, part: "2_town_places", word: "center", meaning: "中心・センター" },
    { id: 1024, part: "2_town_places", word: "village", meaning: "村" },
    { id: 1025, part: "2_town_places", word: "theater", meaning: "劇場・映画館" },

    // --- ③ 自然・環境・地球 (3_nature_env) ---
    { id: 1026, part: "3_nature_env", word: "earth", meaning: "地球・土" },
    { id: 1027, part: "3_nature_env", word: "nature", meaning: "自然" },
    { id: 1028, part: "3_nature_env", word: "plant", meaning: "植物・工場" },
    { id: 1029, part: "3_nature_env", word: "field", meaning: "野原・グラウンド" },
    { id: 1030, part: "3_nature_env", word: "forest", meaning: "森・森林" },
    { id: 1031, part: "3_nature_env", word: "beach", meaning: "浜辺・ビーチ" },
    { id: 1032, part: "3_nature_env", word: "island", meaning: "島" },
    { id: 1033, part: "3_nature_env", word: "air", meaning: "空気" },
    { id: 1034, part: "3_nature_env", word: "fire", meaning: "火・火事" },
    { id: 1035, part: "3_nature_env", word: "space", meaning: "宇宙・空間" },
    { id: 1036, part: "3_nature_env", word: "environment", meaning: "環境" },
    { id: 1037, part: "3_nature_env", word: "recycling", meaning: "リサイクル" },

    // --- ④ 職業・人と社会 (4_jobs_society) ---
    { id: 1038, part: "4_jobs_society", word: "doctor", meaning: "医者" },
    { id: 1039, part: "4_jobs_society", word: "nurse", meaning: "看護師" },
    { id: 1040, part: "4_jobs_society", word: "driver", meaning: "運転手" },
    { id: 1041, part: "4_jobs_society", word: "pilot", meaning: "操縦士・パイロット" },
    { id: 1042, part: "4_jobs_society", word: "police officer", meaning: "警察官" },
    { id: 1043, part: "4_jobs_society", word: "farmer", meaning: "農家" },
    { id: 1044, part: "4_jobs_society", word: "writer", meaning: "作家" },
    { id: 1045, part: "4_jobs_society", word: "singer", meaning: "歌手" },
    { id: 1046, part: "4_jobs_society", word: "actor", meaning: "俳優" },
    { id: 1047, part: "4_jobs_society", word: "artist", meaning: "芸術家・画家" },
    { id: 1048, part: "4_jobs_society", word: "guest", meaning: "客・ゲスト" },
    { id: 1049, part: "4_jobs_society", word: "neighbor", meaning: "近所の人・隣人" },
    { id: 1050, part: "4_jobs_society", word: "stranger", meaning: "見知らぬ人" },
    { id: 1051, part: "4_jobs_society", word: "clerk", meaning: "店員" },
    { id: 1052, part: "4_jobs_society", word: "customer", meaning: "客・顧客" },
    { id: 1053, part: "4_jobs_society", word: "volunteer", meaning: "ボランティア" },
    { id: 1054, part: "4_jobs_society", word: "society", meaning: "社会" },

    // --- ⑤ 気持ち・心の動詞 (5_mind_verbs) ---
    { id: 1055, part: "5_mind_verbs", word: "remember", meaning: "覚えている・思い出す" },
    { id: 1056, part: "5_mind_verbs", word: "forget", meaning: "忘れる" },
    { id: 1057, part: "5_mind_verbs", word: "understand", meaning: "理解する" },
    { id: 1058, part: "5_mind_verbs", word: "explain", meaning: "説明する" },
    { id: 1059, part: "5_mind_verbs", word: "agree", meaning: "同意する" },
    { id: 1060, part: "5_mind_verbs", word: "decide", meaning: "決める" },
    { id: 1061, part: "5_mind_verbs", word: "hope", meaning: "望む・願う" },
    { id: 1062, part: "5_mind_verbs", word: "believe", meaning: "信じる" },
    { id: 1063, part: "5_mind_verbs", word: "worry", meaning: "心配する" },
    { id: 1064, part: "5_mind_verbs", word: "surprise", meaning: "驚かせる" },
    { id: 1065, part: "5_mind_verbs", word: "excite", meaning: "興奮させる" },

    // --- ⑥ 変化・移動の動詞 (6_action_verbs) ---
    { id: 1066, part: "6_action_verbs", word: "borrow", meaning: "借りる" },
    { id: 1067, part: "6_action_verbs", word: "lend", meaning: "貸す" },
    { id: 1068, part: "6_action_verbs", word: "invite", meaning: "招待する" },
    { id: 1069, part: "6_action_verbs", word: "receive", meaning: "受け取る" },
    { id: 1070, part: "6_action_verbs", word: "choose", meaning: "選ぶ" },
    { id: 1071, part: "6_action_verbs", word: "collect", meaning: "集める" },
    { id: 1072, part: "6_action_verbs", word: "reach", meaning: "到着する・手を伸ばす" },
    { id: 1073, part: "6_action_verbs", word: "arrive", meaning: "到着する" },
    { id: 1074, part: "6_action_verbs", word: "leave", meaning: "去る・出発する・残す" },
    { id: 1075, part: "6_action_verbs", word: "return", meaning: "戻る・返す" },
    { id: 1076, part: "6_action_verbs", word: "move", meaning: "動く・引っ越す" },
    { id: 1077, part: "6_action_verbs", word: "travel", meaning: "旅行する" },
    { id: 1078, part: "6_action_verbs", word: "climb", meaning: "登る" },
    { id: 1079, part: "6_action_verbs", word: "protect", meaning: "保護する・守る" },
    { id: 1080, part: "6_action_verbs", word: "repair", meaning: "修理する" },
    { id: 1081, part: "6_action_verbs", word: "build", meaning: "建てる" },

    // --- ⑦ 状態・評価の形容詞 (7_adjectives) ---
    { id: 1082, part: "7_adjectives", word: "difficult", meaning: "難しい" },
    { id: 1083, part: "7_adjectives", word: "important", meaning: "重要な" },
    { id: 1084, part: "7_adjectives", word: "useful", meaning: "役に立つ" },
    { id: 1085, part: "7_adjectives", word: "convenient", meaning: "便利な" },
    { id: 1086, part: "7_adjectives", word: "necessary", meaning: "必要な" },
    { id: 1087, part: "7_adjectives", word: "possible", meaning: "可能な" },
    { id: 1088, part: "7_adjectives", word: "impossible", meaning: "不可能な" },
    { id: 1089, part: "7_adjectives", word: "popular", meaning: "人気のある" },
    { id: 1090, part: "7_adjectives", word: "famous", meaning: "有名な" },
    { id: 1091, part: "7_adjectives", word: "special", meaning: "特別な" },
    { id: 1092, part: "7_adjectives", word: "international", meaning: "国際的な" },
    { id: 1093, part: "7_adjectives", word: "foreign", meaning: "外国の" },
    { id: 1094, part: "7_adjectives", word: "local", meaning: "地元の" },
    { id: 1095, part: "7_adjectives", word: "comfortable", meaning: "快適な" },
    { id: 1096, part: "7_adjectives", word: "dangerous", meaning: "危険な" },
    { id: 1097, part: "7_adjectives", word: "polite", meaning: "礼儀正しい" },
    { id: 1098, part: "7_adjectives", word: "nervous", meaning: "緊張している" },

    // --- ⑧ 様子・度合いの副詞 (8_adverbs) ---
    { id: 1099, part: "8_adverbs", word: "easily", meaning: "簡単に" },
    { id: 1100, part: "8_adverbs", word: "quickly", meaning: "素早く" },
    { id: 1101, part: "8_adverbs", word: "slowly", meaning: "ゆっくりと" },
    { id: 1102, part: "8_adverbs", word: "carefully", meaning: "注意深く" },
    { id: 1103, part: "8_adverbs", word: "clearly", meaning: "はっきりと" },
    { id: 1104, part: "8_adverbs", word: "suddenly", meaning: "急に・突然" },
    { id: 1105, part: "8_adverbs", word: "finally", meaning: "ついに・最後に" },
    { id: 1106, part: "8_adverbs", word: "actually", meaning: "実際に・実は" },
    { id: 1107, part: "8_adverbs", word: "especially", meaning: "特に" },
    { id: 1108, part: "8_adverbs", word: "almost", meaning: "ほとんど" },
    { id: 1109, part: "8_adverbs", word: "maybe", meaning: "たぶん" },
    { id: 1110, part: "8_adverbs", word: "probably", meaning: "十中八九・きっと" },

    // --- ⑨ 重要熟語・連語 (9_phrases) ---
    { id: 1111, part: "9_phrases", word: "be good at", meaning: "〜が得意である" },
    { id: 1112, part: "9_phrases", word: "be bad at", meaning: "〜が苦手である" },
    { id: 1113, part: "9_phrases", word: "be interested in", meaning: "〜に興味がある" },
    { id: 1114, part: "9_phrases", word: "be late for", meaning: "〜に遅れる" },
    { id: 1115, part: "9_phrases", word: "be afraid of", meaning: "〜を恐れる" },
    { id: 1116, part: "9_phrases", word: "be proud of", meaning: "〜を誇りに思う" },
    { id: 1117, part: "9_phrases", word: "look forward to", meaning: "〜を楽しみに待つ" },
    { id: 1118, part: "9_phrases", word: "take care of", meaning: "〜の世話をする" },
    { id: 1119, part: "9_phrases", word: "take part in", meaning: "〜に参加する" },
    { id: 1120, part: "9_phrases", word: "make friends with", meaning: "〜と友達になる" },
    { id: 1121, part: "9_phrases", word: "give up", meaning: "諦める" },
    { id: 1122, part: "9_phrases", word: "pick up", meaning: "拾う・車で迎える" },
    { id: 1123, part: "9_phrases", word: "grow up", meaning: "成長する" },
    { id: 1124, part: "9_phrases", word: "all over the world", meaning: "世界中で" },
    { id: 1125, part: "9_phrases", word: "at the same time", meaning: "同時に" },
    { id: 1126, part: "9_phrases", word: "for the first time", meaning: "初めて" },
    { id: 1127, part: "9_phrases", word: "by the way", meaning: "ところで" },

    // --- ⑩ 会話・日常フレーズ (10_conversations) ---
    { id: 1128, part: "10_conversations", word: "May I help you?", meaning: "いらっしゃいませ・お手伝いしましょうか" },
    { id: 1129, part: "10_conversations", word: "How much is this?", meaning: "これはいくらですか" },
    { id: 1130, part: "10_conversations", word: "I'll take it.", meaning: "これにします・買います" },
    { id: 1131, part: "10_conversations", word: "What's wrong?", meaning: "どうしましたか？" },
    { id: 1132, part: "10_conversations", word: "That's too bad.", meaning: "それはお気の毒に" },
    { id: 1133, part: "10_conversations", word: "Why don't we...?", meaning: "〜しませんか" },
    { id: 1134, part: "10_conversations", word: "Sounds great!", meaning: "いいですね！" },
    { id: 1135, part: "10_conversations", word: "How long does it take?", meaning: "どのくらい時間がかかりますか" },
    { id: 1136, part: "10_conversations", word: "Have a nice day!", meaning: "良い一日を！" },
    { id: 1137, part: "10_conversations", word: "Congratulations!", meaning: "おめでとう！" },
    { id: 1138, part: "10_conversations", word: "Good luck!", meaning: "頑張って！" },
    { id: 1139, part: "10_conversations", word: "Help yourself.", meaning: "ご自由にどうぞ" },
    { id: 1140, part: "10_conversations", word: "Never mind.", meaning: "気にしないで" }
  ]
};
