const initialWords = [
  // --- Part 1 (1〜200: 名詞・身の回り・学校・食べ物など) ---
  { id: 1, part: "part1", word: "book", meaning: "本" },
  { id: 2, part: "part1", word: "pen", meaning: "ペン" },
  { id: 3, part: "part1", word: "pencil", meaning: "鉛筆" },
  { id: 4, part: "part1", word: "desk", meaning: "つくえ" },
  { id: 5, part: "part1", word: "chair", meaning: "いす" },
  { id: 6, part: "part1", word: "bag", meaning: "かばん" },
  { id: 7, part: "part1", word: "notebook", meaning: "ノート" },
  { id: 8, part: "part1", word: "box", meaning: "箱" },
  { id: 9, part: "part1", word: "clock", meaning: "時計" },
  { id: 10, part: "part1", word: "picture", meaning: "写真・絵" },
  { id: 11, part: "part1", word: "computer", meaning: "コンピュータ" },
  { id: 12, part: "part1", word: "phone", meaning: "電話" },
  { id: 13, part: "part1", word: "school", meaning: "学校" },
  { id: 14, part: "part1", word: "classroom", meaning: "教室" },
  { id: 15, part: "part1", word: "teacher", meaning: "先生" },
  { id: 16, part: "part1", word: "student", meaning: "生徒" },
  { id: 17, part: "part1", word: "friend", meaning: "友達" },
  { id: 18, part: "part1", word: "class", "meaning": "授業・クラス" },
  { id: 19, part: "part1", word: "homework", meaning: "宿題" },
  { id: 20, part: "part1", word: "test", meaning: "テスト" },
  { id: 21, part: "part1", word: "house", meaning: "家" },
  { id: 22, part: "part1", word: "room", meaning: "部屋" },
  { id: 23, part: "part1", word: "door", meaning: "ドア" },
  { id: 24, part: "part1", word: "window", meaning: "窓" },
  { id: 25, part: "part1", word: "table", meaning: "テーブル" },
  { id: 26, part: "part1", word: "bed", meaning: "ベッド" },
  { id: 27, part: "part1", word: "kitchen", meaning: "台所" },
  { id: 28, part: "part1", word: "park", meaning: "公園" },
  { id: 29, part: "part1", word: "station", meaning: "駅" },
  { id: 30, part: "part1", word: "hospital", meaning: "病院" },
  { id: 31, part: "part1", word: "library", meaning: "図書館" },
  { id: 32, part: "part1", word: "bus", meaning: "バス" },
  { id: 33, part: "part1", word: "car", meaning: "車" },
  { id: 34, part: "part1", word: "train", meaning: "電車" },
  { id: 35, part: "part1", word: "bike", meaning: "自転車" },
  { id: 36, part: "part1", word: "plane", meaning: "飛行機" },
  { id: 37, part: "part1", word: "father", meaning: "お父さん" },
  { id: 38, part: "part1", word: "mother", meaning: "お母さん" },
  { id: 39, part: "part1", word: "brother", meaning: "兄弟（兄・弟）" },
  { id: 40, part: "part1", word: "sister", meaning: "姉妹（姉・妹）" },
  { id: 41, part: "part1", word: "family", meaning: "家族" },
  { id: 42, part: "part1", word: "dog", meaning: "犬" },
  { id: 43, part: "part1", word: "cat", meaning: "猫" },
  { id: 44, part: "part1", word: "bird", meaning: "鳥" },
  { id: 45, part: "part1", word: "fish", meaning: "魚" },
  { id: 46, part: "part1", word: "apple", meaning: "りんご" },
  { id: 47, part: "part1", word: "water", meaning: "水" },
  { id: 48, part: "part1", word: "milk", meaning: "牛乳" },
  { id: 49, part: "part1", word: "bread", meaning: "パン" },
  { id: 50, part: "part1", word: "rice", meaning: "ご飯・米" },
  // ... (以下、同様にID:51〜200までPart1の名詞・日常単語を拡張格納)

  // --- Part 2 (201〜400: 動詞・形容詞・副詞) ---
  { id: 201, part: "part2", word: "go", meaning: "行く" },
  { id: 202, part: "part2", word: "come", meaning: "来る" },
  { id: 203, part: "part2", word: "see", meaning: "見る・会う" },
  { id: 204, part: "part2", word: "look", meaning: "見る" },
  { id: 205, part: "part2", word: "listen", meaning: "聴く" },
  { id: 206, part: "part2", word: "hear", meaning: "聞こえる" },
  { id: 207, part: "part2", word: "speak", meaning: "話す" },
  { id: 208, part: "part2", word: "talk", meaning: "話す・しゃべる" },
  { id: 209, part: "part2", word: "say", meaning: "言う" },
  { id: 210, part: "part2", word: "eat", meaning: "食べる" },
  { id: 211, part: "part2", word: "drink", meaning: "飲む" },
  { id: 212, part: "part2", word: "read", meaning: "読む" },
  { id: 213, part: "part2", word: "write", meaning: "書く" },
  { id: 214, part: "part2", word: "study", meaning: "勉強する" },
  { id: 215, part: "part2", word: "play", meaning: "遊ぶ・(スポーツを)する" },
  { id: 216, part: "part2", word: "run", meaning: "走る" },
  { id: 217, part: "part2", word: "walk", meaning: "歩く" },
  { id: 218, part: "part2", word: "swim", meaning: "泳ぐ" },
  { id: 219, part: "part2", word: "sing", meaning: "歌う" },
  { id: 220, part: "part2", word: "make", meaning: "作る" },
  { id: 221, part: "part2", word: "big", meaning: "大きい" },
  { id: 222, part: "part2", word: "small", meaning: "小さい" },
  { id: 223, part: "part2", word: "good", meaning: "良い" },
  { id: 224, part: "part2", word: "bad", meaning: "悪い" },
  { id: 225, part: "part2", word: "new", meaning: "新しい" },
  { id: 226, part: "part2", word: "old", meaning: "古い・年をとった" },
  { id: 227, part: "part2", word: "happy", meaning: "幸せな・嬉しい" },
  { id: 228, part: "part2", word: "sad", meaning: "悲しい" },
  { id: 229, part: "part2", word: "hot", meaning: "熱い・暑い" },
  { id: 230, part: "part2", word: "cold", meaning: "冷たい・寒い" },
  // ... (以下、同様にID:231〜400までPart2の動詞・形容詞を拡張格納)

  // --- Part 3 (401〜600: 疑問詞・前置詞・熟語・会話表現) ---
  { id: 401, part: "part3", word: "what", meaning: "何" },
  { id: 402, part: "part3", word: "who", meaning: "誰" },
  { id: 403, part: "part3", word: "where", meaning: "どこ" },
  { id: 404, part: "part3", word: "when", meaning: "いつ" },
  { id: 405, part: "part3", word: "why", meaning: "なぜ" },
  { id: 406, part: "part3", word: "how", meaning: "どのように・どれくらい" },
  { id: 407, part: "part3", word: "in", meaning: "〜の中に" },
  { id: 408, part: "part3", word: "on", meaning: "〜の上に" },
  { id: 409, part: "part3", word: "under", meaning: "〜の下に" },
  { id: 410, part: "part3", word: "at", meaning: "〜で・〜に" },
  { id: 411, part: "part3", word: "get up", meaning: "起きる" },
  { id: 412, part: "part3", word: "go to bed", meaning: "寝る" },
  { id: 413, part: "part3", word: "come in", meaning: "入る" },
  { id: 414, part: "part3", word: "sit down", meaning: "座る" },
  { id: 415, part: "part3", word: "stand up", meaning: "立つの" },
  { id: 416, part: "part3", word: "look at", meaning: "〜を見る" },
  { id: 417, part: "part3", word: "listen to", meaning: "〜を聴く" },
  { id: 418, part: "part3", word: "after school", meaning: "放課後" },
  { id: 419, part: "part3", word: "of course", meaning: "もちろん" },
  { id: 420, part: "part3", word: "welcome to", meaning: "〜へようこそ" }
  // ... (以下、同様にID:421〜600までPart3の熟語・表現を拡張格納)
];